### ISSUE TITLE
NPE @ Full2VideoRecorder.java line 79

### ISSUE THREAD

**Issue by jonathanlmarsh** [natario1/CameraView#1010]
### Describe the bug
We are getting crash reports in production coming from this library @ Full2VideoRecorder.java line 79. There does not appear to a single manufacturer, device, or API this is limited to. It is also unclear at the moment how to reproduce this issue, but so far for the last 30 days I have nearly 90 crashes due to this.

- CameraView version: 2.6.3
- Camera engine used: camera2
- Reproducible in official demo app: no
- Device / Android version: All (our app supports 6+)
- I have read the [FAQ page](https://natario1.github.io/CameraView/about/faq): yes

### To Reproduce
Steps to reproduce the behavior, possibly in the demo app:
1. Steps are currently unknown

### Expected behavior
It seems in the SDK this value is assumed to be non-nullable but actually appears to be nullable so it seems like the `prepareMediaRecorder` needs to check for null and return false or `FullVideoRecorder.onStart` needs to check that it isn't passing a `null` value into `prepareMediaRecorder`.

### XML layout
Part of the XML layout with the CameraView declaration, so we can read its attributes.

```xml
<com.otaliastudios.cameraview.CameraView
      android:id="@+id/camera"
      android:layout_width="match_parent"
      android:layout_height="match_parent"
      android:keepScreenOn="true"
      app:cameraGesturePinch="zoom"
      app:cameraGestureTap="autoFocus"
      ...
      />
```

### Stacktrace
```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'int com.otaliastudios.cameraview.VideoResult$Stub.rotation' on a null object reference
       at com.otaliastudios.cameraview.video.Full2VideoRecorder.getCamcorderProfile(Full2VideoRecorder.java:79)
       at com.otaliastudios.cameraview.video.FullVideoRecorder.prepareMediaRecorder(FullVideoRecorder.java:85)
       at com.otaliastudios.cameraview.video.FullVideoRecorder.prepareMediaRecorder(FullVideoRecorder.java:76)
       at com.otaliastudios.cameraview.video.FullVideoRecorder.onStart(FullVideoRecorder.java:307)
       at com.otaliastudios.cameraview.video.Full2VideoRecorder.access$001(Full2VideoRecorder.java:27)
       at com.otaliastudios.cameraview.video.Full2VideoRecorder$2.onActionCompleted(Full2VideoRecorder.java:59)
       at com.otaliastudios.cameraview.engine.action.CompletionCallback.onActionStateChanged(CompletionCallback.java:18)
       at com.otaliastudios.cameraview.engine.action.BaseAction.setState(BaseAction.java:116)
       at com.otaliastudios.cameraview.video.Full2VideoRecorder$1.onCaptureStarted(Full2VideoRecorder.java:52)
       at com.otaliastudios.cameraview.engine.Camera2Engine$1.onCaptureStarted(Camera2Engine.java:275)
       at java.lang.reflect.Method.invoke(Method.java)
       at android.hardware.camera2.dispatch.InvokeDispatcher.dispatch(InvokeDispatcher.java:39)
       at android.hardware.camera2.dispatch.HandlerDispatcher$1.run(HandlerDispatcher.java:65)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by namboy19** [comment]
I have same issue  when press record video and imediately stop record
