### ISSUE TITLE
Rare crash: Fatal Exception: java.lang.RuntimeException: takePicture failed

### ISSUE THREAD

**Issue by michaelspecht** [natario1/CameraView#1023]
We are using your wonderful library (and loving it) in an enterprise application, but we found that we are seeing a crash with maybe 10 out of every 20,000 pictures taken on the devices we use (CAT s48c). We've seen it with both Camera1 and Camera2, and, given where it is crashing, I think it is likely a hardware issue, rather than an issue with the library or our implementation. I propose wrapping the take call to `takePicture()` within a try/catch, so that the app can choose what to do in the event of picture failure (right now, the whole app crashes). I've created a PR with this approach, but would welcome any alternatives or feedback!

- CameraView version: 2.6.4
- Camera engine used: both
- Device / Android version: Android 8.1.0, CAT s48c
- I have read the [FAQ page](https://natario1.github.io/CameraView/about/faq): yes

### Stack Trace of Crash
```
Fatal Exception: java.lang.RuntimeException: takePicture failed
       at android.hardware.Camera.native_takePicture(Camera.java)
       at android.hardware.Camera.takePicture(Camera.java:1589)
       at com.otaliastudios.cameraview.picture.Full1PictureRecorder.take(Full1PictureRecorder.java:47)
       at com.otaliastudios.cameraview.engine.Camera1Engine.onTakePicture(Camera1Engine.java:380)
       at com.otaliastudios.cameraview.engine.CameraBaseEngine$3.run(CameraBaseEngine.java:522)
       at com.otaliastudios.cameraview.engine.orchestrator.CameraStateOrchestrator$3.run(CameraStateOrchestrator.java:100)
       at com.otaliastudios.cameraview.engine.orchestrator.CameraOrchestrator$1.call(CameraOrchestrator.java:75)
       at com.otaliastudios.cameraview.engine.orchestrator.CameraOrchestrator$1.call(CameraOrchestrator.java:72)
       at com.otaliastudios.cameraview.engine.orchestrator.CameraOrchestrator$2.onComplete(CameraOrchestrator.java:100)
       at com.otaliastudios.cameraview.engine.orchestrator.CameraOrchestrator$4.run(CameraOrchestrator.java:195)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.os.HandlerThread.run(HandlerThread.java:65)
```

### Expected behavior
No crash at the very least, ideally would call the onCameraError callback

### XML layout
Part of the XML layout with the CameraView declaration, so we can read its attributes.

```xml
<com.otaliastudios.cameraview.CameraView
        android:id="@+id/camera"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center"
        android:layout_marginBottom="88dp"
        android:keepScreenOn="true"
        app:cameraExperimental="true"
        app:cameraEngine="camera2"
        app:cameraPreview="glSurface"
        app:cameraPlaySounds="true"
        app:cameraGrid="off"
        app:cameraFlash="auto"
        app:cameraAudio="on"
        app:cameraFacing="back"
        app:cameraGestureTap="autoFocus"
        app:cameraGestureLongTap="none"
        app:cameraGesturePinch="zoom"
        app:cameraGestureScrollHorizontal="filterControl1"
        app:cameraGestureScrollVertical="exposureCorrection"
        app:cameraMode="picture"
        app:cameraAutoFocusMarker="@string/cameraview_default_autofocus_marker">
```

**Comment by Landi29** [comment]
From reading the Pull Request, i guess that the issue is solved.
