### ISSUE TITLE
While second time start recording that raised below issue : 

### ISSUE THREAD

**Issue by sathishmscict** [natario1/CameraView#1038]
I/CameraCallbacks: dispatchError com.otaliastudios.cameraview.CameraException: java.lang.RuntimeException: Internal Camera1 error. 2
    com.otaliastudios.cameraview.CameraException: java.lang.RuntimeException: Internal Camera1 error. 2
        at com.otaliastudios.cameraview.engine.Camera1Engine.onError(Camera1Engine.java:92)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1262)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.RuntimeException: Internal Camera1 error. 2
        at com.otaliastudios.cameraview.engine.Camera1Engine.onError(Camera1Engine.java:82)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1262) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
2021-01-23 17:18:37.110 30360-30360/com.quantumpigeon.saturn I/CameraCallbacks: dispatchOnCameraClosed
2021-01-23 17:18:37.111 30360-30360/com.quantumpigeon.saturn D/BottomSheetVideoRecording$Listener: onCameraError called 3

Here am using :

<com.otaliastudios.cameraview.CameraView
                android:id="@+id/cameraView"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_gravity="center"
                android:keepScreenOn="true"
                app:cameraExperimental="false"
                app:cameraEngine="camera2"
                app:cameraPreview="glSurface"
                app:cameraPlaySounds="true"
                app:cameraGrid="off"
                app:cameraFlash="auto"
                app:cameraAudio="on"
                app:cameraFacing="front"
                app:cameraGestureTap="autoFocus"
                app:cameraGestureLongTap="none"
                app:cameraGesturePinch="none"
                app:cameraGestureScrollHorizontal="none"
                app:cameraGestureScrollVertical="zoom"
                app:cameraMode="video"
                app:cameraAutoFocusMarker="@string/cameraview_default_autofocus_marker"/>

Am using this code in bottom sheet. 
If user click and hold start video recording once time limit completed and release holded button programatically stopped that video recording and save recorder video in device.
This is flow working fine for first time, second time again bottom sheet is open for recording than above issue raised. Same sheet if we close and open 1 more time than working fine and 2nd time again not working. Above mentioned error raised.

**Comment by rezznov** [comment]
same here
can someone please help.
the third time I navigate to a fragment which has cameraview I face the same error for recording video
