### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.SurfaceTexture.setDefaultBufferSize(int, int)' on a null object referenc

### ISSUE THREAD

**Issue by faldujaldeep** [natario1/CameraView#1057]
Please check this issue found from the Crashlytics.

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.SurfaceTexture.setDefaultBufferSize(int, int)' on a null object reference
       at com.otaliastudios.cameraview.engine.Camera2Engine.onStartBind(Camera2Engine.java:506)
       at com.otaliastudios.cameraview.engine.CameraEngine$8.call(CameraEngine.java:470)
       at com.otaliastudios.cameraview.engine.CameraEngine$8.call(CameraEngine.java:466)
       at com.otaliastudios.cameraview.engine.orchestrator.CameraStateOrchestrator$2.call(CameraStateOrchestrator.java:69)
       at com.otaliastudios.cameraview.engine.orchestrator.CameraStateOrchestrator$2.call(CameraStateOrchestrator.java:60)
       at com.otaliastudios.cameraview.engine.orchestrator.CameraOrchestrator$2.onComplete(CameraOrchestrator.java:100)
       at com.google.android.gms.tasks.zzj.run(com.google.android.gms:play-services-tasks@@17.2.0:4)
       at com.otaliastudios.cameraview.internal.WorkerHandler.run(WorkerHandler.java:137)
       at com.otaliastudios.cameraview.internal.WorkerHandler$2.execute(WorkerHandler.java:112)
       at com.google.android.gms.tasks.zzi.zza(com.google.android.gms:play-services-tasks@@17.2.0:10)
       at com.google.android.gms.tasks.zzq.zza(com.google.android.gms:play-services-tasks@@17.2.0:19)
       at com.google.android.gms.tasks.zzu.zzb(com.google.android.gms:play-services-tasks@@17.2.0:112)
       at com.google.android.gms.tasks.TaskCompletionSource.trySetResult(com.google.android.gms:play-services-tasks@@17.2.0:10)
       at com.otaliastudios.cameraview.engine.orchestrator.CameraOrchestrator$2$1.onComplete(CameraOrchestrator.java:116)
       at com.google.android.gms.tasks.zzj.run(com.google.android.gms:play-services-tasks@@17.2.0:4)
       at com.otaliastudios.cameraview.internal.WorkerHandler.run(WorkerHandler.java:137)
       at com.otaliastudios.cameraview.internal.WorkerHandler$2.execute(WorkerHandler.java:112)
       at com.google.android.gms.tasks.zzi.zza(com.google.android.gms:play-services-tasks@@17.2.0:10)
       at com.google.android.gms.tasks.zzq.zza(com.google.android.gms:play-services-tasks@@17.2.0:19)
       at com.google.android.gms.tasks.zzu.zza(com.google.android.gms:play-services-tasks@@17.2.0:104)
       at com.google.android.gms.tasks.zzd.onSuccess(com.google.android.gms:play-services-tasks@@17.2.0:8)
       at com.google.android.gms.tasks.zzn.run(com.google.android.gms:play-services-tasks@@17.2.0:4)
       at com.google.android.gms.tasks.zzt.execute(com.google.android.gms:play-services-tasks@@17.2.0:2)
       at com.google.android.gms.tasks.zzm.zza(com.google.android.gms:play-services-tasks@@17.2.0:11)
       at com.google.android.gms.tasks.zzq.zza(com.google.android.gms:play-services-tasks@@17.2.0:19)
       at com.google.android.gms.tasks.zzu.zzb(com.google.android.gms:play-services-tasks@@17.2.0:112)
       at com.google.android.gms.tasks.TaskCompletionSource.trySetResult(com.google.android.gms:play-services-tasks@@17.2.0:10)
       at com.otaliastudios.cameraview.engine.Camera2Engine$2.onOpened(Camera2Engine.java:427)
       at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:139)
       at android.os.Handler.handleCallback(Handler.java:795)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:166)
       at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by wisnuwiry** [comment]
How to fix this issue?
