### ISSUE TITLE
setParameter failed at Camera1Engine.java line 527

### ISSUE THREAD

**Issue by faisalramd** [natario1/CameraView#1063]
### Describe the bug
I'm getting this log error at our crashlytics, probably this happened when user setting flash on/ off.

Please add a clear description of what the bug is, **and** fill the list below.
- CameraView version: 2.6.4
- Camera engine used: both
- Reproducible in official demo app: not sure
- Device / Android version: (Redmi 4X, Android 7.1.2) (vivo 1718, Android 8.1.0)
- I have read the [FAQ page](https://natario1.github.io/CameraView/about/faq): yes

### Expected behavior
Crash not happened when setting flash on/ off.

### XML layout
Part of the XML layout with the CameraView declaration, so we can read its attributes.

```xml
<com.otaliastudios.cameraview.CameraView
    android:id="@+id/camera_view"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layout_gravity="center"
    android:keepScreenOn="true"
    app:cameraGestureLongTap="none"
    app:cameraGesturePinch="zoom"
    app:cameraGestureScrollHorizontal="none"
    app:cameraGestureScrollVertical="none"
    app:cameraGestureTap="autoFocus"
    app:cameraGrid="off"
    app:cameraFlash="off"
    app:cameraPlaySounds="true"
    app:cameraAudio="off"
    app:cameraMode="picture"
    app:cameraFacing="back" />
```

### Logs
**Camera1Engine.java line 527**
```
Fatal Exception: java.lang.RuntimeException: setParameters failed
       at android.hardware.Camera.native_setParameters(Camera.java)
       at android.hardware.Camera.setParameters(Camera.java:2045)
       at com.otaliastudios.cameraview.engine.Camera1Engine$1.run(Camera1Engine.java:527)
       at com.otaliastudios.cameraview.engine.orchestrator.CameraStateOrchestrator$3.run(CameraStateOrchestrator.java:100)
       at com.otaliastudios.cameraview.engine.orchestrator.CameraOrchestrator$1.call(CameraOrchestrator.java:75)
       at com.otaliastudios.cameraview.engine.orchestrator.CameraOrchestrator$1.call(CameraOrchestrator.java:72)
       at com.otaliastudios.cameraview.engine.orchestrator.CameraOrchestrator$2.onComplete(CameraOrchestrator.java:100)
       at com.otaliastudios.cameraview.engine.orchestrator.CameraOrchestrator$4.run(CameraOrchestrator.java:195)
       at android.os.Handler.handleCallback(Handler.java:754)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:163)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by cuibg** [comment]
this bug is not belong to this repository！
