### ISSUE TITLE
A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.

### ISSUE THREAD

**Issue by wuyu9527** [natario1/CameraView#1075]
E: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'release' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:180)
        at android.view.Surface.setNativeObjectLocked(Surface.java:511)
        at android.view.Surface.<init>(Surface.java:179)
        at com.otaliastudios.cameraview.engine.Camera2Engine.onStartBind(Camera2Engine.java:520)
        at com.otaliastudios.cameraview.engine.CameraEngine$8.call(CameraEngine.java:470)
        at com.otaliastudios.cameraview.engine.CameraEngine$8.call(CameraEngine.java:466)
        at com.otaliastudios.cameraview.engine.orchestrator.CameraStateOrchestrator$2.call(CameraStateOrchestrator.java:69)
        at com.otaliastudios.cameraview.engine.orchestrator.CameraStateOrchestrator$2.call(CameraStateOrchestrator.java:60)
        at com.otaliastudios.cameraview.engine.orchestrator.CameraOrchestrator$3.run(CameraOrchestrator.java:152)
        at com.otaliastudios.cameraview.internal.WorkerHandler.run(WorkerHandler.java:137)
        at com.otaliastudios.cameraview.engine.orchestrator.CameraOrchestrator.execute(CameraOrchestrator.java:147)
        at com.otaliastudios.cameraview.engine.orchestrator.CameraOrchestrator.access$100(CameraOrchestrator.java:34)
        at com.otaliastudios.cameraview.engine.orchestrator.CameraOrchestrator$2.run(CameraOrchestrator.java:137)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)

Not released after the page has been closed.
Try adding  
 surface.release(); 
Hope it helps

**Comment by yangjieK** [comment]
yes I got the same problem.  Bro, How did you fix it? Lets share it
