### ISSUE TITLE
Huawei P30 (Android 9): Demo app crashes on Video capture

### ISSUE THREAD

**Issue by jmonaniat** [natario1/CameraView#1121]
### Describe the bug
Please add a clear description of what the bug is, **and** fill the list below.
- CameraView version: *version number* : 2.7.1
- Camera engine used: *camera1/camera2/both* : camera2
- Reproducible in official demo app: *yes/no* - Yes
- Device / Android version: *Pixel, API 28* - Wuawei P30 model ELE-L29 API 28
- I have read the [FAQ page](https://natario1.github.io/CameraView/about/faq): *yes/no* : yes

### To Reproduce
Steps to reproduce the behavior, possibly in the demo app:
1. Go to edit and change the mode to video
2. Click on video icon image
3. See error  Toast message "Got Exception 3"

### Expected behavior
Video successfully captured and stored into a file to be shared.

### XML layout
Part of the XML layout with the CameraView declaration, so we can read its attributes.

```xml
<CameraView
    android:layout_width="match_parent"
    android:layout_height="match_parent"       
    ...>
</CameraView>
```

### Logs
Use `CameraLogger.setLogLevel(LEVEL_INFO)` to see all logs into LogCat.
2021-08-09 11:20:51.517 28701-28817/com.otaliastudios.cameraview.demo W/FullVideoRecorder: stop: Error while closing media recorder. java.lang.RuntimeException: stop failed.
    java.lang.RuntimeException: stop failed.
        at android.media.MediaRecorder.native_stop(Native Method)
        at android.media.MediaRecorder.stop(MediaRecorder.java:1610)
        at com.otaliastudios.cameraview.video.FullVideoRecorder.onStop(FullVideoRecorder.java:331)
        at com.otaliastudios.cameraview.video.VideoRecorder.stop(VideoRecorder.java:98)
        at com.otaliastudios.cameraview.video.FullVideoRecorder$1.onInfo(FullVideoRecorder.java:276)
        at android.media.MediaRecorder$EventHandler.handleMessage(MediaRecorder.java:1339)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2021-08-09 11:20:51.518 28701-28817/com.otaliastudios.cameraview.demo I/FullVideoRecorder: stop: Releasing MediaRecorder...
2021-08-09 11:20:51.524 28701-28817/com.otaliastudios.cameraview.demo I/FullVideoRecorder: stop: Released MediaRecorder.
2021-08-09 11:20:51.524 28701-28817/com.otaliastudios.cameraview.demo I/VideoRecorder: dispatchResult: Changed state to STATE_IDLE.
2021-08-09 11:20:51.524 28701-28817/com.otaliastudios.cameraview.demo I/VideoRecorder: dispatchResult: About to dispatch result: null java.lang.RuntimeException: stop failed.
    java.lang.RuntimeException: stop failed.
        at android.media.MediaRecorder.native_stop(Native Method)
        at android.media.MediaRecorder.stop(MediaRecorder.java:1610)
        at com.otaliastudios.cameraview.video.FullVideoRecorder.onStop(FullVideoRecorder.java:331)
        at com.otaliastudios.cameraview.video.VideoRecorder.stop(VideoRecorder.java:98)
        at com.otaliastudios.cameraview.video.FullVideoRecorder$1.onInfo(FullVideoRecorder.java:276)
        at android.media.MediaRecorder$EventHandler.handleMessage(MediaRecorder.java:1339)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2021-08-09 11:20:51.525 28701-28817/com.otaliastudios.cameraview.demo E/CameraEngine: onVideoResult result is null: something went wrong. java.lang.RuntimeException: stop failed.
    java.lang.RuntimeException: stop failed.
        at android.media.MediaRecorder.native_stop(Native Method)
        at android.media.MediaRecorder.stop(MediaRecorder.java:1610)
        at com.otaliastudios.cameraview.video.FullVideoRecorder.onStop(FullVideoRecorder.java:331)
        at com.otaliastudios.cameraview.video.VideoRecorder.stop(VideoRecorder.java:98)
        at com.otaliastudios.cameraview.video.FullVideoRecorder$1.onInfo(FullVideoRecorder.java:276)
        at android.media.MediaRecorder$EventHandler.handleMessage(MediaRecorder.java:1339)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2021-08-09 11:20:51.526 28701-28817/com.otaliastudios.cameraview.demo I/CameraCallbacks: dispatchError com.otaliastudios.cameraview.CameraException: java.lang.RuntimeException: stop failed.
    com.otaliastudios.cameraview.CameraException: java.lang.RuntimeException: stop failed.
        at com.otaliastudios.cameraview.engine.CameraBaseEngine.onVideoResult(CameraBaseEngine.java:670)
        at com.otaliastudios.cameraview.engine.Camera2Engine.onVideoResult(Camera2Engine.java:973)
        at com.otaliastudios.cameraview.video.VideoRecorder.dispatchResult(VideoRecorder.java:138)
        at com.otaliastudios.cameraview.video.FullVideoRecorder.onStop(FullVideoRecorder.java:359)
        at com.otaliastudios.cameraview.video.VideoRecorder.stop(VideoRecorder.java:98)
        at com.otaliastudios.cameraview.video.FullVideoRecorder$1.onInfo(FullVideoRecorder.java:276)
        at android.media.MediaRecorder$EventHandler.handleMessage(MediaRecorder.java:1339)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: java.lang.RuntimeException: stop failed.
        at android.media.MediaRecorder.native_stop(Native Method)
        at android.media.MediaRecorder.stop(MediaRecorder.java:1610)
        at com.otaliastudios.cameraview.video.FullVideoRecorder.onStop(FullVideoRecorder.java:331)
        at com.otaliastudios.cameraview.video.VideoRecorder.stop(VideoRecorder.java:98) 
        at com.otaliastudios.cameraview.video.FullVideoRecorder$1.onInfo(FullVideoRecorder.java:276) 
        at android.media.MediaRecorder$EventHandler.handleMessage(MediaRecorder.java:1339) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 

Use `CameraLogger.registerLogger()` to export to file or crash reporting service.

### APK
Link to a Github repo where the bug is reproducible.
https://github.com/natario1/CameraView/tree/main/demo

**Comment by jmonaniat** [comment]
Hello @natario1,

Can you or anyone can take a look at this issue?

Thanks
Jignesh

**Comment by jmonaniat** [comment]
Hi @natario1,
Following up to see if anything else needed or wonder in case setup call or communicate via email, please let me know.

Thanks,
Jignesh
