### ISSUE TITLE
NutlPointerException: Attempt to read from field 'int android.view.view.mviewFlags' on a nult object reference

### ISSUE THREAD

**Issue by xiaotian317** [natario1/CameraView#1132]
### Describe the bug
Please add a clear description of what the bug is, **and** fill the list below.
- CameraView version: *2.7.1*
- Camera engine used: *camera2*
- Reproducible in official demo app: *no*
- Device / Android version: *Google Pixel 3, API 30*
- I have read the [FAQ page](https://natario1.github.io/CameraView/about/faq): *yes*

2021-09-17 11:23:33.485 21787-25362/cn.carya E/AndroidRuntime: FATAL EXCEPTION: VideoEncoder
Process:cn.carya,PID:21787
java.lang.NutlPointerException: Attempt to read from field 'int android.view.view.mviewFlags' on a nult object reference
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4276) 
at android.view.View.draw(View.java:22353)
at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4429) 
at android.view.View.draw(View.java:22223)
at android.view.ViewGroup.drawChild(ViewGroup.java:4516) 
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277) 
at android.view.View.draw(View.java:22221)
at android.view.ViewGroup.drawChild(ViewGroup.java:4516) 
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277) 
at android.view.View.draw(View.java:22221)
at android.view.ViewGroup.drawchild(ViewGroup.java:4516)
at com.otaliastudios.cameraview.overlay.OverlavLavout.drawChild(OverlavLavout.iava:169) 
at com.otaliastudios.cameraview.overlay.0verlayLayout.doDrawChild(OverlayLayout.java:180)

**Comment by TheMilanTej** [comment]
I have the same issue can you get the solution?
