### ISSUE TITLE
 Fatal Exception: java.lang.NullPointerException Attempt to invoke virtual method 'int com.otaliastudios.cameraview.size.Size.getWidth()' on a null object reference

### ISSUE THREAD

**Issue by elephant16** [natario1/CameraView#1136]
### Describe the bug
- CameraView version: 2.7.1
- Camera engine used: camera2
- Reproducible in official demo app:no*
- Device / Android version: Galaxy S20, API 30 and other
- I have read the [FAQ page](https://natario1.github.io/CameraView/about/faq): yes

### To Reproduce
When I call takeSnapshot. It sometimes occurs on some devices

### Expected behavior
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.otaliastudios.cameraview.size.Size.getWidth()' on a null object reference
       at com.otaliastudios.cameraview.internal.CropHelper.computeCrop(CropHelper.java:18)
       at com.otaliastudios.cameraview.picture.SnapshotGlPictureRecorder.onRendererTextureCreated(SnapshotGlPictureRecorder.java:111)
       at com.otaliastudios.cameraview.picture.SnapshotGlPictureRecorder$1.onRendererTextureCreated(SnapshotGlPictureRecorder.java:84)
       at com.otaliastudios.cameraview.preview.GlCameraPreview$2.run(GlCameraPreview.java:301)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1520)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1286)

### XML layout

```xml
<com.otaliastudios.cameraview.CameraView
    android:id="@+id/cameraView"
    app:cameraAudio="off"
    app:cameraAutoFocusMarker="@string/cameraview_default_autofocus_marker"
    app:cameraEngine="camera2"
    app:cameraExperimental="true"
    app:cameraFacing="back"
    app:cameraFlash="auto"
    app:cameraGestureLongTap="none"
    app:cameraGesturePinch="zoom"
    app:cameraGestureScrollHorizontal="zoom"
    app:cameraGestureScrollVertical="exposureCorrection"
    app:cameraGestureTap="autoFocus"
    app:cameraGrid="off"
    app:cameraWhiteBalance="auto"
    app:cameraMode="picture"
    app:cameraPictureFormat="jpeg"
    app:cameraPlaySounds="false"
    app:cameraPreview="glSurface"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:keepScreenOn="true"
    app:cameraUseDeviceOrientation="true"
    android:layout_marginBottom="48dp"
    />
```

### Logs
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.otaliastudios.cameraview.size.Size.getWidth()' on a null object reference
       at com.otaliastudios.cameraview.internal.CropHelper.computeCrop(CropHelper.java:18)
       at com.otaliastudios.cameraview.picture.SnapshotGlPictureRecorder.onRendererTextureCreated(SnapshotGlPictureRecorder.java:111)
       at com.otaliastudios.cameraview.picture.SnapshotGlPictureRecorder$1.onRendererTextureCreated(SnapshotGlPictureRecorder.java:84)
       at com.otaliastudios.cameraview.preview.GlCameraPreview$2.run(GlCameraPreview.java:301)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1520)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1286)

**Comment by usmanrana-ilsa** [comment]
Facing same issue, any solution?
