### ISSUE TITLE
PictureResult.getData() returns null on some devices after onPictureTaken() in CameraListener()

### ISSUE THREAD

**Issue by GhassenMsd** [natario1/CameraView#1168]
### Describe the bug
Please add a clear description of what the bug is, **and** fill the list below.
- CameraView version: *2.7.2*
- Camera engine used: *camera1*
- Reproducible in official demo app: *unknonw*
- Device / Android version: *Samsung SM-G980F, Google Pixel 5 API 31*
- I have read the [FAQ page](https://natario1.github.io/CameraView/about/faq): *yes*

### To Reproduce
Steps to reproduce the behavior, possibly in the demo app:
- I can't reproduce myself, we are receiving bugsnags on some devices on our production app.

### Expected behavior
- Not crashing maybe or handle the error.

### XML layout
Part of the XML layout with the CameraView declaration, so we can read its attributes.

```xml
<com.otaliastudios.cameraview.CameraView
        android:id="@+id/view_camera"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:cameraAudio="off"
        app:cameraFacing="back"
        app:cameraMode="picture"
        app:cameraPictureFormat="jpeg"
        app:cameraUseDeviceOrientation="false" />
```

### Screenshots
<img width="1134" alt="Capture d’écran 2022-05-03 à 09 59 46" src="https://user-images.githubusercontent.com/57293098/166428069-11b23cae-0413-4ad9-ae4c-fa9da82b686f.png">

### Logs
java.lang.NullPointerException · Attempt to get length of null arrayRawCameraUtils:317 com.otaliastudios.cameraview.CameraUtils.decodeBitmapCameraUtils:34 com.otaliastudios.cameraview.CameraUtils.access$000CameraUtils.java:216 com.otaliastudios.cameraview.CameraUtils$2.runHandler.java:938 android.os.Handler.handleCallbackHandler.java:99 android.os.Handler.dispatchMessageLooper.java:226 android.os.Looper.loopOnceLooper.java:313 android.os.Looper.loopHandlerThread.java:67 android.os.HandlerThread.run

### APK
Link to a Github repo where the bug is reproducible.

**Comment by qsdigor** [comment]
Similar issue here but this time it is for writing empty data to OutputStream

```
Fatal Exception: java.lang.NullPointerException: Attempt to get length of null array
       at java.io.FilterOutputStream.write(FilterOutputStream.java:103)
       at com.otaliastudios.cameraview.CameraUtils.writeToFile(CameraUtils.java:93)
       at com.otaliastudios.cameraview.CameraUtils$1.run(CameraUtils.java:121)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.os.HandlerThread.run(HandlerThread.java:67)
```
