### ISSUE TITLE
 camera recording adaptation failed

### ISSUE THREAD

**Issue by jianwenzhou** [natario1/CameraView#1186]
Hello, the camera recording adaptation failed, the error code is CameraException.REASON_VIDEO_FAILED

```xml
 <com.otaliastudios.cameraview.CameraView
        android:id="@+id/detect_preview_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:cameraAudio="off"
        app:cameraMode="video"
        app:cameraFacing="front"
        app:cameraFlash="auto"
        app:cameraEngine="camera2"
        app:cameraVideoSizeBiggest="false" />
```

### Logs
08-11 16:45:57.936  6976  7096 E CameraEngine: onVideoResult result is null: something went wrong. java.lang.RuntimeException: start failed.
08-11 16:45:57.936  6976  7096 E CameraEngine: java.lang.RuntimeException: start failed.
08-11 16:45:57.936  6976  7096 E CameraEngine: 	at android.media.MediaRecorder.start(Native Method)
08-11 16:45:57.936  6976  7096 E CameraEngine: 	at com.otaliastudios.cameraview.video.FullVideoRecorder.onStart(FullVideoRecorder.java:314)
08-11 16:45:57.936  6976  7096 E CameraEngine: 	at com.otaliastudios.cameraview.video.VideoRecorder.start(VideoRecorder.java:80)
08-11 16:45:57.936  6976  7096 E CameraEngine: 	at com.otaliastudios.cameraview.engine.Camera1Engine.onTakeVideo(Camera1Engine.java:426)
08-11 16:45:57.936  6976  7096 E CameraEngine: 	at com.otaliastudios.cameraview.engine.CameraBaseEngine$5.run(CameraBaseEngine.java:605)
08-11 16:45:57.936  6976  7096 E CameraEngine: 	at com.otaliastudios.cameraview.engine.orchestrator.CameraStateOrchestrator$3.run(CameraStateOrchestrator.java:100)
08-11 16:45:57.936  6976  7096 E CameraEngine: 	at com.otaliastudios.cameraview.engine.orchestrator.CameraOrchestrator$1.call(CameraOrchestrator.java:84)
08-11 16:45:57.936  6976  7096 E CameraEngine: 	at com.otaliastudios.cameraview.engine.orchestrator.CameraOrchestrator$1.call(CameraOrchestrator.java:81)
08-11 16:45:57.936  6976  7096 E CameraEngine: 	at com.otaliastudios.cameraview.engine.orchestrator.CameraOrchestrator$3.run(CameraOrchestrator.java:152)
08-11 16:45:57.936  6976  7096 E CameraEngine: 	at com.otaliastudios.cameraview.internal.WorkerHandler.run(WorkerHandler.java:137)
08-11 16:45:57.936  6976  7096 E CameraEngine: 	at com.otaliastudios.cameraview.engine.orchestrator.CameraOrchestrator.execute(CameraOrchestrator.java:147)
08-11 16:45:57.936  6976  7096 E CameraEngine: 	at com.otaliastudios.cameraview.engine.orchestrator.CameraOrchestrator.access$100(CameraOrchestrator.java:34)
08-11 16:45:57.936  6976  7096 E CameraEngine: 	at com.otaliastudios.cameraview.engine.orchestrator.CameraOrchestrator$2.run(CameraOrchestrator.java:137)
08-11 16:45:57.936  6976  7096 E CameraEngine: 	at android.os.Handler.handleCallback(Handler.java:938)
08-11 16:45:57.936  6976  7096 E CameraEngine: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-11 16:45:57.936  6976  7096 E CameraEngine: 	at android.os.Looper.loopOnce(Looper.java:233)
08-11 16:45:57.936  6976  7096 E CameraEngine: 	at android.os.Looper.loop(Looper.java:344)
08-11 16:45:57.936  6976  7096 E CameraEngine: 	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by kai0421-A** [comment]
I had this problem too
