### ISSUE TITLE
NullPointerException at GlTextureDrawer.setFilter

### ISSUE THREAD

**Issue by EzequielAdrianM** [natario1/CameraView#1236]
```
Fatal Exception: java.lang.NullPointerException: Attempt to write to field 'e9.b i9.e.d' on a null object reference
       at com.otaliastudios.cameraview.internal.GlTextureDrawer.setFilter(GlTextureDrawer.java:49)
       at com.otaliastudios.cameraview.picture.SnapshotGlPictureRecorder.onRendererFilterChanged(SnapshotGlPictureRecorder.java:122)
       at com.otaliastudios.cameraview.picture.SnapshotGlPictureRecorder$1.onRendererFilterChanged(SnapshotGlPictureRecorder.java:90)
       at com.otaliastudios.cameraview.preview.GlCameraPreview$2.run(GlCameraPreview.java:303)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1500)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
```

It looks like somehow, at line (49) of GlTextureDrawer.java, the function setFilter is receiving a null argument thus causing NonNull annotation to raise the exception.

```
public void setFilter(@NonNull Filter filter) {
        mPendingFilter = filter;
    }
```

Maybe the NonNull annotation should be removed? Can the app continue working if mPendingFilter is null?
This exception appeared at random just in one device in production environment.

**Comment by ShakeelAziz** [comment]
Facing the same issue, Any one know how to solve this?

**Comment by big-guogai** [comment]
Facing the same issue, Any one know how to solve this?

**Comment by abbas427** [comment]
I'm also facing the same issue, any update on this issue?
