### ISSUE TITLE
error when call takePicture() method?

### ISSUE THREAD

**Issue by klower** [natario1/CameraView#1249]
com.otaliastudios.cameraview.CameraException: java.lang.RuntimeException: Internal Camera1 error. 2
                                                                                                    	at com.otaliastudios.cameraview.engine.Camera1Engine.onError(Camera1Engine.java:92)
                                                                                                    	at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1160)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                                    	at android.os.Looper.loop(Looper.java:164)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:65)
                                                                                                    Caused by: java.lang.RuntimeException: Internal Camera1 error. 2
                                                                                                    	at com.otaliastudios.cameraview.engine.Camera1Engine.onError(Camera1Engine.java:82)
                                                                                                    	at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1160) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                                                    	at android.os.Looper.loop(Looper.java:164) 
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:65) 

<img width="617" alt="image" src="https://github.com/natario1/CameraView/assets/4176873/e1b740b0-148d-4abd-8dcf-e243aa3ad8c8">

**Comment by klower** [comment]
xml:
<com.otaliastudios.cameraview.CameraView
        android:id="@+id/camera"
        android:layout_width="match_parent"
        app:cameraAudio="off"
        app:cameraAutoFocusMarker="@string/cameraview_default_autofocus_marker"
        app:cameraEngine="camera2"
        app:cameraFlash="auto"
        app:cameraGestureTap="autoFocus"
        app:cameraMode="picture"
        app:cameraPictureFormat="jpeg"
        app:cameraPictureSizeAspectRatio="16:9"
        app:cameraPictureSizeBiggest="true"
        app:cameraPlaySounds="false"
        app:cameraPreview="glSurface"
        app:cameraRequestPermissions="true"
        app:cameraUseDeviceOrientation="true"
        android:layout_height="match_parent">

**Comment by klower** [comment]
@natario1 would you please take some time to fix issue?
