### ISSUE TITLE
IllegalStateException: Unable to update texture contents (see logcat for details)

### ISSUE THREAD

**Issue by casanovawu** [natario1/CameraView#1253]
[SurfaceTexture-19-21130-19] checkAndUpdateEglState: invalid current EGLContext
updateAcquireFence: Did not find frame.
FATAL EXCEPTION: VideoEncoder
Process: cc.shantu.syxj, PID: 21130
java.lang.IllegalStateException: Unable to update texture contents (see logcat for details)
	at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
	at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:251)
	at com.otaliastudios.cameraview.overlay.OverlayDrawer.draw(OverlayDrawer.java:81)
	at com.otaliastudios.cameraview.video.encoding.TextureMediaEncoder.onFrame(TextureMediaEncoder.java:218)
	at com.otaliastudios.cameraview.video.encoding.TextureMediaEncoder.onEvent(TextureMediaEncoder.java:146)
	at com.otaliastudios.cameraview.video.encoding.MediaEncoder$3.run(MediaEncoder.java:244)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:223)
	at android.os.Looper.loop(Looper.java:324)
	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by casanovawu** [comment]
During the video recording process, there was an exception in continuously starting/pausing the recording

**Comment by KangJuO** [comment]
Same here..
