### ISSUE TITLE
FATAL EXCEPTION: VideoEncoder java.lang.IllegalStateException: writeSampleData returned an error

### ISSUE THREAD

**Issue by an-droida** [natario1/CameraView#1275]
### Logs
FATAL EXCEPTION: VideoEncoder
java.lang.IllegalStateException: writeSampleData returned an error
at android.media.MediaMuxer.nativeWriteSampleData(Native Method)
at android.media.MediaMuxer.writeSampleData(MediaMuxer.java:723)
at com.otaliastudios.cameraview.video.encoding.MediaEncoderEngine$Controller.write(MediaEncoderEngine.java:362)
at com.otaliastudios.cameraview.video.encoding.MediaEncoder.onWriteOutput(MediaEncoder.java:502)
at com.otaliastudios.cameraview.video.encoding.VideoMediaEncoder.onWriteOutput(VideoMediaEncoder.java:126)
at com.otaliastudios.cameraview.video.encoding.MediaEncoder.drainOutput(MediaEncoder.java:472)
at com.otaliastudios.cameraview.video.encoding.TextureMediaEncoder.onFrame(TextureMediaEncoder.java:187)
at com.otaliastudios.cameraview.video.encoding.TextureMediaEncoder.onEvent(TextureMediaEncoder.java:146)
at com.otaliastudios.cameraview.video.encoding.MediaEncoder$3.run(MediaEncoder.java:244)
at android.os.Handler.handleCallback(Handler.java:959)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loopOnce(Looper.java:232)
at android.os.Looper.loop(Looper.java:317)
at android.os.HandlerThread.run(HandlerThread.java:82)

**Comment by mohammednawas8** [comment]
I am encountering this issue too
