### ISSUE TITLE
NPE in ScrollGestureLayout

### ISSUE THREAD

**Issue by xp-vit** [natario1/CameraView#180]
*If you are trying to report a bug, please file the information below.
Prerequisites:*

- [x ] *I am using the latest version*
- [ ] *I can reproduce the bug in the demo app, and if not...*
- [ x] *I have tried to reproduce the bug in the demo app*

#### Detailed steps to reproduce the issue:
Don't know!

#### Interesting logs:

I see NPEs being reported by users. Here is the stacktrace:
`#0. Crashed: main
       at com.otaliastudios.cameraview.ScrollGestureLayout$1.onScroll(ScrollGestureLayout.java:32)
       at android.view.GestureDetector.onTouchEvent(GestureDetector.java:619)
       at com.otaliastudios.cameraview.ScrollGestureLayout.onTouchEvent(ScrollGestureLayout.java:66)
       at com.otaliastudios.cameraview.CameraView.onTouchEvent(CameraView.java:473)
       at android.view.View.dispatchTouchEvent(View.java:9314)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2592)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2283)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2598)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2297)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2598)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2297)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2598)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2297)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2598)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2297)
       at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2430)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent_aroundBody0(PhoneWindow.java:1762)
       at com.android.internal.policy.PhoneWindow$AjcClosure1.run(PhoneWindow.java:1)
       at android.view.PhoneWindowAO.ajc$around$android_view_PhoneWindowAO$4$99ce526bproceed(PhoneWindowAO.aj:149)
       at android.view.PhoneWindowAO.ajc$around$android_view_PhoneWindowAO$4$99ce526b(PhoneWindowAO.aj:153)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1762)
       at android.app.Activity.dispatchTouchEvent(Activity.java:2807)
       at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2391)
       at android.view.View.dispatchPointerEvent(View.java:9534)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4422)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4288)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3739)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3792)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3758)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3766)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3739)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3792)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3758)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3885)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3766)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3942)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3739)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3792)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3758)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3766)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3739)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6146)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6120)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6081)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6278)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(InputEventReceiver.java)
       at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
       at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6228)
       at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6301)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
       at android.view.Choreographer.doCallbacks(Choreographer.java:670)
       at android.view.Choreographer.doFrame(Choreographer.java:600)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5585)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)

--

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'float android.view.MotionEvent.getX()' on a null object reference
       at com.otaliastudios.cameraview.ScrollGestureLayout$1.onScroll(ScrollGestureLayout.java:32)
       at android.view.GestureDetector.onTouchEvent(GestureDetector.java:619)
       at com.otaliastudios.cameraview.ScrollGestureLayout.onTouchEvent(ScrollGestureLayout.java:66)
       at com.otaliastudios.cameraview.CameraView.onTouchEvent(CameraView.java:473)
       at android.view.View.dispatchTouchEvent(View.java:9314)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2592)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2283)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2598)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2297)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2598)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2297)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2598)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2297)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2598)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2297)
       at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2430)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent_aroundBody0(PhoneWindow.java:1762)
       at com.android.internal.policy.PhoneWindow$AjcClosure1.run(PhoneWindow.java:1)
       at android.view.PhoneWindowAO.ajc$around$android_view_PhoneWindowAO$4$99ce526bproceed(PhoneWindowAO.aj:149)
       at android.view.PhoneWindowAO.ajc$around$android_view_PhoneWindowAO$4$99ce526b(PhoneWindowAO.aj:153)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1762)
       at android.app.Activity.dispatchTouchEvent(Activity.java:2807)
       at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2391)
       at android.view.View.dispatchPointerEvent(View.java:9534)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4422)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4288)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3739)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3792)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3758)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3766)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3739)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3792)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3758)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3885)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3766)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3942)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3739)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3792)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3758)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3766)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3739)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6146)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6120)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6081)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6278)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(InputEventReceiver.java)
       at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
       at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6228)
       at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6301)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
       at android.view.Choreographer.doCallbacks(Choreographer.java:670)
       at android.view.Choreographer.doFrame(Choreographer.java:600)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5585)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)`

**Comment by natario1** [comment]
Thanks, looks like a bug. Should be easy to fix, do you have some time to do this?
