### ISSUE TITLE
setParameters failed (after focus?)

### ISSUE THREAD

**Issue by chiyan171** [natario1/CameraView#188]
cameraview's version：compile 'com.otaliastudios:cameraview:1.5.0'

Tested system's version: 5.1、5.1.1、6.0.1、7.0
BUG's Mobile model:
OPPO R9s、 R9s Plust、R9m 
HUAWEI P9、Honor V8  
VIVO X7 5.1
Galaxy-A9(2016)

Fatal Exception: java.lang.RuntimeException: setParameters failed
       at android.hardware.Camera.native_setParameters(Camera.java)
       at android.hardware.Camera.setParameters(Camera.java:1999)
       at com.otaliastudios.cameraview.Camera1$19.run(Camera1.java:806)
       at com.otaliastudios.cameraview.Camera1$2.run(Camera1.java:62)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:179)
       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by natario1** [comment]
Thanks for the report.
