### ISSUE TITLE
RuntimeException

### ISSUE THREAD

**Issue by Seachal** [natario1/CameraView#204]
*If you are trying to report a bug, please file the information below.
Prerequisites:*

- [ ] *I am using the latest version    1.5.0

FATAL EXCEPTION: main
                                                                              Process: seachal.com.cameraphotoframe, PID: 15845
                                                                              java.lang.RuntimeException: startPreview failed
                                                                                  at android.hardware.Camera.startPreview(Native Method)
                                                                                  at com.otaliastudios.cameraview.Camera1.applySizesAndStartPreview(Camera1.java:160)
                                                                                  at com.otaliastudios.cameraview.Camera1.bindToSurface(Camera1.java:134)
                                                                                  at com.otaliastudios.cameraview.Camera1.onStart(Camera1.java:191)
                                                                                  at com.otaliastudios.cameraview.CameraController$3.run(CameraController.java:180)
                                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                  at android.os.Looper.loop(Looper.java:135)
                                                                                  at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by natario1** [comment]
Duplicate issue
