### ISSUE TITLE
CameraView in Fragment throws NPE

### ISSUE THREAD

**Issue by jeremy-jamez** [natario1/CameraView#3]
I'm implementing CameraView in a fragment and app crashes when trying to open said fragment:
`                                                                --------- beginning of crash
08-26 18:51:53.625 30605-30605/com.pictematic E/AndroidRuntime: FATAL EXCEPTION: main
                                                                Process: com.pictematic, PID: 30605
                                                                java.lang.RuntimeException: Unable to resume activity {com.pictematic/com.pictematic.CameraActivity}: java.lang.NullPointerException: Attempt to read from field 'com.otaliastudios.cameraview.CameraView com.pictematic.PostFragments.CameraPreviewFragment.cameraView' on a null object reference
                                                                    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3469)
                                                                    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3509)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2772)
                                                                    at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1507)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:154)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:6236)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
                                                                 Caused by: java.lang.NullPointerException: Attempt to read from field 'com.otaliastudios.cameraview.CameraView com.pictematic.PostFragments.CameraPreviewFragment.cameraView' on a null object reference
                                                                    at com.pictematic.CameraActivity.onResume(CameraActivity.java:113)
                                                                    at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1270)
                                                                    at android.app.Activity.performResume(Activity.java:6788)
                                                                    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3446)
                                                                    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3509) 
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2772) 
                                                                    at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1507) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                    at android.os.Looper.loop(Looper.java:154) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:6236) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781) `

onResume, onPause and onDestroy are called from the parent activity:

`@Override
    protected void onDestroy() {
        super.onDestroy();
        CameraPreviewFragment cameraPreviewFragment = (CameraPreviewFragment) getSupportFragmentManager().findFragmentById(R.id.cameraView);
        cameraPreviewFragment.cameraView.destroy();
    }

    @Override
    protected void onPause() {
        super.onPause();
        CameraPreviewFragment cameraPreviewFragment = (CameraPreviewFragment) getSupportFragmentManager().findFragmentById(R.id.cameraView);
        cameraPreviewFragment.cameraView.stop();
    }

    @Override
    protected void onResume() {
        super.onResume();
        CameraPreviewFragment cameraPreviewFragment = (CameraPreviewFragment) getSupportFragmentManager().findFragmentById(R.id.cameraView);
        cameraPreviewFragment.cameraView.start();
    }`

CameraView reference in Fragment: 
`@BindView(R.id.cameraView)
    public CameraView cameraView;`

CameraView listener in onCreate:
`cameraView.addCameraListener(new CameraListener() {
            @Override
            public void onPictureTaken(byte[] jpeg) {
                super.onPictureTaken(jpeg);
                mCapturingPicture = false;
                long callbackTime = System.currentTimeMillis();

                if (mCapturingVideo) {
                    //message("Captured while taking video. Size= "+mCaptureNativeSize, false);
                    return;
                }

                CameraActivity.setImage(jpeg);
                //Intent intent = new Intent(getContext(), CameraActivity.class);
                //startActivity(intent);
                writeToFile(jpeg);

            }

            @Override
            public void onVideoTaken(File video) {
                super.onVideoTaken(video);
                mListener.onFragmentInteraction(Uri.fromFile(video));
            }
        });`

**Comment by natario1** [comment]
Doesn't look like a bug in the library. Your fragment is null at the time of onResume.

If you are using CameraView inside a fragment, you should use the fragment callbacks (`onResume`, `onPause` etc.).
