### ISSUE TITLE
CI-Process: Maven & JCenter Version crashes & different Versions in Maven vs. JCenter

### ISSUE THREAD

**Issue by ffischer1984** [natario1/CameraView#320]
*If you are trying to report a bug, please file the information below.
Prerequisites:*

- [x] *I am using the latest version*
- [ ] *I can reproduce the bug in the demo app, and if not...*
  - the source-code of the github repository works fine (master-branch) but on the [JCenter](https://mvnrepository.com/artifact/com.otaliastudios/cameraview?repo=jcenter) the lib crashes while a picture is being captured
- [x] *I have tried to reproduce the bug in the demo app*
  - to crash the demo-app I have removed the local-dependency and inserted the JCenter dependency (1.6.0) of the camera-view. Checkout [this](https://github.com/ffischer1984/CameraView/commit/5fade3c73ac283c7bd0cc8ebe295004cbc09a154) to reproduce the behaviour

#### Detailed steps to reproduce the issue:
1. Checkout this [commit](https://github.com/ffischer1984/CameraView/commit/5fade3c73ac283c7bd0cc8ebe295004cbc09a154)
2. capture a photo

#### Actual behavior:
crashes

#### Expected behavior:
same versions in the repositories:
[JCenter](https://mvnrepository.com/artifact/com.otaliastudios/cameraview?repo=jcenter) vs. [Spring Plugins](https://mvnrepository.com/artifact/com.otaliastudios/cameraview?repo=springio-plugins-release) 
- mark one as deprecated
- mention it in the readme.me

#### Interesting logs:

Process: com.otaliastudios.cameraview.demo, PID: 3592
    java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/media/ExifInterface;
        at com.otaliastudios.cameraview.CameraUtils.decodeBitmap(CameraUtils.java:140)
        at com.otaliastudios.cameraview.CameraUtils$1.run(CameraUtils.java:105)
        at android.os.Handler.handleCallback(Handler.java:869)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:206)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.media.ExifInterface" on path: DexPathList[[zip file "/data/app/com.otaliastudios.cameraview.demo-f-rF7kga9bG7UB5vThItOQ==/base.apk", zip file "/data/app/com.otaliastudios.cameraview.demo-f-rF7kga9bG7UB5vThItOQ==/split_lib_dependencies_apk.apk", zip file "/data/app/com.otaliastudios.cameraview.demo-f-rF7kga9bG7UB5vThItOQ==/split_lib_resources_apk.apk", zip file "/data/app/com.otaliastudios.cameraview.demo-f-rF7kga9bG7UB5vThItOQ==/split_lib_slice_0_apk.apk", zip file "/data/app/com.otaliastudios.cameraview.demo-f-rF7kga9bG7UB5vThItOQ==/split_lib_slice_1_apk.apk", zip file "/data/app/com.otaliastudios.cameraview.demo-f-rF7kga9bG7UB5vThItOQ==/split_lib_slice_2_apk.apk", zip file "/data/app/com.otaliastudios.cameraview.demo-f-rF7kga9bG7UB5vThItOQ==/split_lib_slice_3_apk.apk", zip file "/data/app/com.otaliastudios.cameraview.demo-f-rF7kga9bG7UB5vThItOQ==/split_lib_slice_4_apk.apk", zip file "/data/app/com.otaliastudios.cameraview.demo-f-rF7kga9bG7UB5vThItOQ==/split_lib_slice_5_apk.apk", zip file "/data/app/com.otaliastudios.cameraview.demo-f-rF7kga9bG7UB5vThItOQ==/split_lib_slice_6_apk.apk", zip file "/data/app/com.otaliastudios.cameraview.demo-f-rF7kga9bG7UB5vThItOQ==/split_lib_slice_7_apk.apk", zip file "/data/app/com.otaliastudios.cameraview.demo-f-rF7kga9bG7UB5vThItOQ==/split_lib_slice_8_apk.apk", zip file "/data/app/com.otaliastudios.cameraview.demo-f-rF7kga9bG7UB5vThItOQ==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.otaliastudios.cameraview.demo-f-rF7kga9bG7UB5vThItOQ==/lib/arm64, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.otaliastudios.cameraview.CameraUtils.decodeBitmap(CameraUtils.java:140) 
        at com.otaliastudios.cameraview.CameraUtils$1.run(CameraUtils.java:105) 
        at android.os.Handler.handleCallback(Handler.java:869) 
        at android.os.Handler.dispatchMessage(Handler.java:101) 
        at android.os.Looper.loop(Looper.java:206) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.otaliastudios.cameraview.demo-f-rF7kga9bG7UB5vThItOQ==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:74)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.<init>(DexPathList.java:157)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:36)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:676)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:709)
        at android.app.LoadedApk.getResources(LoadedApk.java:936)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2246)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5833)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1726)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:206)

**Comment by natario1** [comment]
Seems like something that might be fixed by simply uninstalling the app and installing again?

**Comment by ffischer1984** [comment]
It can be fixed by cloning the Project from GitHub...but i think thats not
the way it should work If you're supporting binaries these should be use
the current project code.

Mattia Iavarone <notifications@github.com> schrieb am So., 16. Dez. 2018,
15:19:
