### ISSUE TITLE
FrameProcessor problem

### ISSUE THREAD

**Issue by Anotherdgf** [natario1/CameraView#327]
*If you are trying to report a bug, please file the information below.
Prerequisites:*

- [ *] *I am using the latest version*
- [ *] *I can reproduce the bug in the demo app.

#### Detailed steps to reproduce the issue:

1.I want to add a callback to get all the frames in FrameProcessor
2.I just changed from `   @WorkerThread
    void process(@NonNull Frame frame);` to `    @WorkerThread
    void process(@NonNull byte[] data,int rotation,Size previewSize);`
 and all some related functions like dispatchFrame
3. I find there is no frame output after I changed the code
Can anyone help!

`11-18 15:12:27.479 31701-31701/? W/System.err: java.io.FileNotFoundException: /jacoco.exec: open failed: EROFS (Read-only file system)
11-18 15:12:27.480 31701-31701/? W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:456)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
        at org.jacoco.agent.rt.internal_8ff85ea.output.FileOutput.openFile(FileOutput.java:67)
        at org.jacoco.agent.rt.internal_8ff85ea.output.FileOutput.startup(FileOutput.java:49)
        at org.jacoco.agent.rt.internal_8ff85ea.Agent.startup(Agent.java:122)
        at org.jacoco.agent.rt.internal_8ff85ea.Agent.getInstance(Agent.java:50)
        at org.jacoco.agent.rt.internal_8ff85ea.Offline.<clinit>(Offline.java:31)
        at com.otaliastudios.cameraview.CameraView.$jacocoInit(CameraView.java)
        at com.otaliastudios.cameraview.CameraView.<clinit>(CameraView.java)
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
        at android.view.LayoutInflater.createView(LayoutInflater.java:607)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
        at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        at com.otaliastudios.cameraview.demo.CameraActivity.onCreate(CameraActivity.java:55)
        at android.app.Activity.performCreate(Activity.java:6222)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2295)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2407)
        at android.app.ActivityThread.access$800(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1319)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5288)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)
    Caused by: android.system.ErrnoException: open failed: EROFS (Read-only file system)`

**Comment by natario1** [comment]
Can't help you about this, sorry. Try asking on SO.
