### ISSUE TITLE
CameraView.capturePicture is Crashing in Android 7.1

### ISSUE THREAD

**Issue by junaidwarsi1994** [natario1/CameraView#330]
I Am Recieving this Error Whenever i Tried to Invoke capturePicture()
 method

 java.lang.RuntimeException: takePicture failed
       at android.hardware.Camera.native_takePicture(Camera.java)
       at android.hardware.Camera.takePicture(Camera.java:1434)
       at com.otaliastudios.cameraview.Camera1$12.run(Camera1.java:507)
       at com.otaliastudios.cameraview.Camera1$2.run(Camera1.java:62)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.os.HandlerThread.run(HandlerThread.java:61)

Can you Please Help me in that Issue

**Comment by wosiu** [comment]
What device are you using?
Also add some more info:
```
<!-- Add [x] inside the brackets -->

- [ ] *I am using the latest version*
- [ ] *I can reproduce the bug in the demo app, and if not...*
- [ ] *I have tried to reproduce the bug in the demo app*
```

**Comment by hitec16** [comment]
> I Am Recieving this Error Whenever i Tried to Invoke capturePicture()
> method
> 
> java.lang.RuntimeException: takePicture failed
> at android.hardware.Camera.native_takePicture(Camera.java)
> at android.hardware.Camera.takePicture(Camera.java:1434)
> at com.otaliastudios.cameraview.Camera1$12.run(Camera1.java:507)
> at com.otaliastudios.cameraview.Camera1$2.run(Camera1.java:62)
> at android.os.Handler.handleCallback(Handler.java:751)
> at android.os.Handler.dispatchMessage(Handler.java:95)
> at android.os.Looper.loop(Looper.java:154)
> at android.os.HandlerThread.run(HandlerThread.java:61)
> 
> Can you Please Help me in that Issue

Try this 
CameraView.setCropOutput(false);
