### ISSUE TITLE
`IndexOutOfBoundsException` on Camera Launch in API 17 (Video Mode)

### ISSUE THREAD

**Issue by TheKalpit** [natario1/CameraView#355]
### Describe the bug
When CameraView is launched in video mode in Android API 17, it crashes.

- CameraView version: 2.0.0-beta01
- Reproducible in official demo app: Not Tested
- Device / Android version: Emulator API 17

### To Reproduce

Here's my code:

        <com.otaliastudios.cameraview.CameraView
            android:id="@+id/cameraView"
            android:layout_width="0dp"
            android:layout_height="0dp"
            android:keepScreenOn="true"
            app:cameraAudio="on"
            app:cameraFacing="back"
            app:cameraFlash="auto"
            app:cameraGesturePinch="zoom"
            app:cameraGestureScrollVertical="zoom"
            app:cameraGestureTap="focusWithMarker"
            app:cameraPictureSizeMaxHeight="800"
            app:cameraPictureSizeMaxWidth="800"
            app:cameraVideoSizeMaxHeight="800"
            app:cameraVideoSizeMaxWidth="800" />

I'm setting mode in kotlin `onCreate`: `cameraView.mode = Mode.VIDEO`

### Expected behavior
Should show camera preview.

### Logs
```
01-03 07:46:07.970 13508-13508/app.package I/dalvikvm: Could not find method android.app.Activity.requestPermissions, referenced from method com.otaliastudios.cameraview.CameraView.requestPermissions
01-03 07:46:07.970 13508-13508/app.package W/dalvikvm: VFY: unable to resolve virtual method 277: Landroid/app/Activity;.requestPermissions ([Ljava/lang/String;I)V
01-03 07:46:07.990 13508-13508/app.package D/dalvikvm: VFY: replacing opcode 0x6e at 0x003b
01-03 07:46:07.990 13508-13508/app.package I/dalvikvm: Could not find method android.content.Context.checkSelfPermission, referenced from method com.otaliastudios.cameraview.CameraView.checkPermissions
01-03 07:46:07.990 13508-13508/app.package W/dalvikvm: VFY: unable to resolve virtual method 310: Landroid/content/Context;.checkSelfPermission (Ljava/lang/String;)I
01-03 07:46:07.990 13508-13508/app.package D/dalvikvm: VFY: replacing opcode 0x6e at 0x001c
01-03 07:46:07.990 13508-13508/app.package I/dalvikvm: Could not find method android.content.Context.checkSelfPermission, referenced from method com.otaliastudios.cameraview.CameraView.checkPermissions
01-03 07:46:07.990 13508-13508/app.package W/dalvikvm: VFY: unable to resolve virtual method 310: Landroid/content/Context;.checkSelfPermission (Ljava/lang/String;)I
01-03 07:46:07.990 13508-13508/app.package D/dalvikvm: VFY: replacing opcode 0x6e at 0x002a
01-03 07:46:08.040 13508-13508/app.package I/WorkerHandler: get: Creating new handler. CameraViewController
01-03 07:46:08.460 13508-13508/app.package I/WorkerHandler: get: Creating new handler. FrameProcessorsWorker
01-03 07:46:08.470 13508-13508/app.package I/dalvikvm: Could not find method android.view.ScaleGestureDetector.setQuickScaleEnabled, referenced from method com.otaliastudios.cameraview.PinchGestureLayout.onInitialize
01-03 07:46:08.480 13508-13508/app.package W/dalvikvm: VFY: unable to resolve virtual method 1057: Landroid/view/ScaleGestureDetector;.setQuickScaleEnabled (Z)V
01-03 07:46:08.480 13508-13508/app.package D/dalvikvm: VFY: replacing opcode 0x6e at 0x002d
01-03 07:46:08.530 13508-13528/app.package V/FA: Activity paused, time: 42723759
01-03 07:46:08.600 13508-13528/app.package D/FA: Logging event (FE): user_engagement(_e), Bundle[{firebase_event_origin(_o)=auto, firebase_screen_id(_si)=7469326945880245767, engagement_time_msec(_et)=2862, firebase_screen_class(_sc)=ImageCaptureHelperActivity}]
01-03 07:46:08.820 13508-13508/app.package I/CameraController: Start: posting runnable. State: STATE_STOPPED
01-03 07:46:08.860 13508-13613/app.package I/CameraController: Start: executing. State: STATE_STOPPED
01-03 07:46:08.860 13508-13613/app.package I/CameraController: Start: about to call onStart() STATE_STARTING
01-03 07:46:08.890 13508-13613/app.package I/Camera1: collectCameraId Facing: BACK Internal: 0 Cameras: 2
01-03 07:46:09.010 13508-13508/app.package W/CameraView: preview: isHardwareAccelerated: true
01-03 07:46:09.030 13508-13508/app.package W/CameraView: onMeasure: surface is not ready. Calling default behavior.
01-03 07:46:09.240 13508-13613/app.package I/Camera1: createCamera: Applying default parameters.
01-03 07:46:09.420 13508-13508/app.package D/EGL_emulation: eglMakeCurrent: 0xb90082b0: ver 2 0
01-03 07:46:09.430 13508-13508/app.package W/CameraView: onMeasure: surface is not ready. Calling default behavior.
01-03 07:46:09.620 13508-13613/app.package I/Camera1: onStart: Ended
01-03 07:46:09.630 13508-13613/app.package I/CameraController: Start: returned from onStart(). Dispatching. STATE_STARTING
01-03 07:46:09.630 13508-13613/app.package I/CameraCallbacks: dispatchOnCameraOpened com.otaliastudios.cameraview.CameraOptions@aeac8bd8
01-03 07:46:09.670 13508-13508/app.package I/CameraCallbacks: onDeviceOrientationChanged 0
01-03 07:46:09.670 13508-13508/app.package I/Choreographer: Skipped 38 frames!  The application may be doing too much work on its main thread.
01-03 07:46:09.740 13508-13617/app.package D/EGL_emulation: eglCreateContext: 0xb91a6a00: maj 2 min 0 rcv 2
01-03 07:46:09.810 13508-13617/app.package D/EGL_emulation: eglMakeCurrent: 0xb91a6a00: ver 2 0
01-03 07:46:10.140 13508-13508/app.package W/CameraView: onMeasure: surface is not ready. Calling default behavior.
01-03 07:46:10.180 13508-13617/app.package I/CameraPreview: dispatchOnOutputSurfaceAvailable: w= 480 h= 800
01-03 07:46:10.180 13508-13617/app.package I/Camera1: onSurfaceAvailable: Size is 480x800
01-03 07:46:10.270 13508-13613/app.package I/Camera1: onSurfaceAvailable: Inside handler. About to bind.
01-03 07:46:10.310 13508-13613/app.package I/Camera1: bindToSurface: Started
01-03 07:46:10.310 13508-13613/app.package W/dalvikvm: threadid=56: thread exiting with uncaught exception (group=0xae474908)
01-03 07:46:10.350 13508-13613/app.package E/CameraController: uncaughtException: Unexpected exception: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
    java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
        at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:251)
        at java.util.ArrayList.get(ArrayList.java:304)
        at com.otaliastudios.cameraview.CameraController.computeCaptureSize(CameraController.java:540)
        at com.otaliastudios.cameraview.Camera1.bindToSurface(Camera1.java:139)
        at com.otaliastudios.cameraview.Camera1.access$500(Camera1.java:24)
        at com.otaliastudios.cameraview.Camera1$3.run(Camera1.java:77)
        at com.otaliastudios.cameraview.Camera1$2.run(Camera1.java:62)
        at android.os.Handler.handleCallback(Handler.java:725)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:137)
        at android.os.HandlerThread.run(HandlerThread.java:60)
01-03 07:46:10.350 13508-13613/app.package I/CameraController: destroy: state: STATE_STARTED
01-03 07:46:10.350 13508-13613/app.package I/CameraController: stopImmediately: State was: STATE_STARTED
01-03 07:46:10.350 13508-13613/app.package I/Camera1: onStop: About to clean up.
01-03 07:46:10.350 13508-13613/app.package D/Camera: app passed NULL surface
01-03 07:46:10.350 13508-13613/app.package I/Camera1: destroyCamera: Clean up. Releasing camera.
01-03 07:46:10.350 13508-13613/app.package I/Camera1: destroyCamera: Clean up. Released camera.
01-03 07:46:10.350 13508-13613/app.package W/Camera1: onStop: Clean up. Returning.
01-03 07:46:10.350 13508-13613/app.package I/CameraController: stopImmediately: Stopped. State is: STATE_STOPPED
01-03 07:46:10.510 13508-13528/app.package V/FA: Logging event: origin=auto,name=user_engagement(_e),params=Bundle[{firebase_event_origin(_o)=auto, firebase_screen_id(_si)=7469326945880245767, engagement_time_msec(_et)=2862, firebase_screen_class(_sc)=ImageCaptureHelperActivity}]
01-03 07:46:10.840 13508-13508/app.package D/EGL_emulation: eglMakeCurrent: 0xb90082b0: ver 2 0
01-03 07:46:10.920 13508-13508/app.package D/AndroidRuntime: Shutting down VM
01-03 07:46:10.920 13508-13508/app.package W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0xae474908)
01-03 07:46:10.950 13508-13528/app.package V/FA: Saving event, name, data size: user_engagement(_e), 81
01-03 07:46:10.970 13508-13528/app.package V/FA: Event recorded: Event{appId='app.package', name='user_engagement(_e)', params=Bundle[{firebase_event_origin(_o)=auto, firebase_screen_id(_si)=7469326945880245767, firebase_screen_class(_sc)=ImageCaptureHelperActivity, engagement_time_msec(_et)=2862}]}
01-03 07:46:10.990 13508-13508/app.package E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
        at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:251)
        at java.util.ArrayList.get(ArrayList.java:304)
        at com.otaliastudios.cameraview.CameraController.computeCaptureSize(CameraController.java:540)
        at com.otaliastudios.cameraview.Camera1.bindToSurface(Camera1.java:139)
        at com.otaliastudios.cameraview.Camera1.access$500(Camera1.java:24)
        at com.otaliastudios.cameraview.Camera1$3.run(Camera1.java:77)
        at com.otaliastudios.cameraview.Camera1$2.run(Camera1.java:62)
        at android.os.Handler.handleCallback(Handler.java:725)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:137)
        at android.os.HandlerThread.run(HandlerThread.java:60)
```

**Comment by ManuEpi** [comment]
Did you tried this on a real device ( not an emulator ) ? I don't think you can access to camera with an Emulator device
