### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "androidx.lifecycle.LifecycleObserver"

### ISSUE THREAD

**Issue by fessmax** [natario1/CameraView#369]
I have some problems when I try to run activity with CameraView. What I did:
1) add to build.gradle `api 'com.otaliastudios:cameraview:2.0.0-beta02'`
2) add to layout CameraView `
    <com.otaliastudios.cameraview.CameraView
        android:id="@+id/camera"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"/>`
After it build is successful. But when I try to call CameraView, crash happens with this error:
```
    Process: com.example.maxim.myapplication, PID: 15547
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.maxim.myapplication/com.example.maxim.myapplication.MainActivity}: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class com.otaliastudios.cameraview.CameraView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class com.otaliastudios.cameraview.CameraView
     Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class com.otaliastudios.cameraview.CameraView
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.otaliastudios.cameraview.CameraView" on path: DexPathList[[zip file "/data/app/com.example.maxim.myapplication-dytmxb5uXK8qiNPPF-G0pQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.maxim.myapplication-dytmxb5uXK8qiNPPF-G0pQ==/lib/x86, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.view.LayoutInflater.createView(LayoutInflater.java:606)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        at com.example.maxim.myapplication.MainActivity.onCreate(MainActivity.java:11)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-01-17 19:30:05.065 15547-15547/com.example.maxim.myapplication E/AndroidRuntime:   Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/LifecycleObserver;
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
                ... 27 more
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.lifecycle.LifecycleObserver" on path: DexPathList[[zip file "/data/app/com.example.maxim.myapplication-dytmxb5uXK8qiNPPF-G0pQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.maxim.myapplication-dytmxb5uXK8qiNPPF-G0pQ==/lib/x86, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                ... 30 more
```
When I try to use v1.6.1 - all is correct, so I add `api 'androidx.lifecycle:lifecycle-common:2.1.0-alpha01'` with 
```
packagingOptions {
        exclude 'META-INF/proguard/androidx-annotations.pro'
    }
``` 
and it works! 
I want to use CameraView without additional dependencies and some excludes of proguard files, so maybe I do something wrong?

**Comment by natario1** [comment]
See #351 . I *think* that you need to migrate your project to androidX in order to use v2. Please reply there for more info.
