### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: enable shutter sound failed

### ISSUE THREAD

**Issue by ankitbatra11** [natario1/CameraView#377]
Crash observed while enabling shutter sound.

```
Fatal Exception: java.lang.RuntimeException: enable shutter sound failed
       at android.hardware.Camera._enableShutterSound(Camera.java)
       at android.hardware.Camera.enableShutterSound(Camera.java:1919)
       at com.otaliastudios.cameraview.c.b(Camera1.java:395)
       at com.otaliastudios.cameraview.c.c(Camera1.java:190)
       at com.otaliastudios.cameraview.d$3.run(CameraController.java:180)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.os.HandlerThread.run(HandlerThread.java:65)
```

- CameraView version: 1.6.0
- Reproducible in official demo app: *no*
- Device / Android version: *OnePlus3, Oreo*

Crash should not happen while enabling shutter sound.

No logs are available since the crash has been reported through Crashlytics.

**Comment by natario1** [comment]
Will take a look, thanks!
