### ISSUE TITLE
mPreview is null at Camera1.unbindFromSurface(150)

### ISSUE THREAD

**Issue by huseyinWA** [natario1/CameraView#384]
### Describe the bug

- CameraView version: *2.0.0-beta2*
- Reproducible in official demo app: *yes/no*
- Device / Android version: *Many Device and OS*

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class com.otaliastudios.cameraview.h.b()' on a null object reference
       at com.otaliastudios.cameraview.Camera1.unbindFromSurface(Camera1.java:150)
       at com.otaliastudios.cameraview.Camera1.onStop(Camera1.java:278)
       at com.otaliastudios.cameraview.CameraController$4.run(CameraController.java:202)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by natario1** [comment]
Thanks, this should not happen

**Comment by huseyinWA** [comment]
I couldn't reproduce but it crashes in production. It has occured after update to 2.0.0-beta2, before I haven't seen.

**Comment by natario1** [comment]
I have added a check so that this does not crash, but this is an usage error, it seems that you are calling open/close when the CameraView object is not attached to any window (an activity or an attached fragment). So, calling open() too early.
