### ISSUE TITLE
Sending LEVEL_VERBOSE logs to crashlytics

### ISSUE THREAD

**Issue by HBiSoft** [natario1/CameraView#439]
I'm experiencing some crashes, but the log doesn't say much:

    Caused by java.lang.RuntimeException: Fail to connect to camera service
       at android.hardware.Camera.(Camera.java:512)
       at android.hardware.Camera.open(Camera.java:357)
       at com.otaliastudios.cameraview.Camera1.createCamera(Camera1.java:224)
       at com.otaliastudios.cameraview.Camera1.onStart(Camera1.java:266)
       at com.otaliastudios.cameraview.CameraController$5.run(CameraController.java:246)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.os.HandlerThread.run(HandlerThread.java:61)

I want to get more detail from this log so that I can see why this is happening.

I implemented the following:

    CameraLogger.setLogLevel(CameraLogger.LEVEL_VERBOSE);
    CameraLogger.registerLogger(new CameraLogger.Logger() {
        @Override
        public void log(int level, @NonNull String tag, @NonNull String message, @Nullable Throwable throwable) {
                
        }
    });

but it is my understanding that `onCameraError` catches the error.

How would I go about catching it in `registerLogger` so that I can send it to `Crashlytics`?

Will I be able to catch it by doing the following:

    CameraLogger.setLogLevel(CameraLogger.LEVEL_VERBOSE);
        CameraLogger.registerLogger(new CameraLogger.Logger() {
            @Override
            public void log(int level, @NonNull String tag, @NonNull String message, @Nullable Throwable throwable) {
                Crashlytics.logException(throwable);
                // or by calling this
                // Crashlytics.log(level, tag, String.valueOf(throwable));
            }
        });

### Version used
cameraview:2.0.0-beta03

**Comment by HBiSoft** [comment]
I just read the documentation again and it says to do the following:

    CameraLogger.registerLogger(new Logger() {
        @Override
        public void log(@LogLevel int level, String tag, String message, @Nullable Throwable throwable) {
            // For example...
            Crashlytics.log(message);
        }
    });

Sorry, I missed it in the docs, closing.
