### ISSUE TITLE
Size.getWidth() NullPointerException

### ISSUE THREAD

**Issue by kleysonr** [natario1/CameraView#456]
Device: AVD Nexus 6 API 26
CameraView version: 2.0.0-beta04

I've been getting the error below with a high frequency. It's something that I cannot simulate or force to happen, it simply 'happens' without any change in the code.

Error log:

```
2019-04-27 10:18:26.011 24639-24659/com.smartnsens.opencvapp D/Camera: app passed NULL surface
2019-04-27 10:18:26.041 24639-24663/com.smartnsens.opencvapp D/EGL_emulation: eglMakeCurrent: 0xa86052a0: ver 2 0 (tinfo 0xa8603380)
2019-04-27 10:18:26.075 24639-24663/com.smartnsens.opencvapp D/EGL_emulation: eglMakeCurrent: 0xa86052a0: ver 2 0 (tinfo 0xa8603380)
2019-04-27 10:18:26.174 24639-24660/com.smartnsens.opencvapp D/skia: onFlyCompress
2019-04-27 10:18:26.231 24639-24660/com.smartnsens.opencvapp E/AndroidRuntime: FATAL EXCEPTION: FrameProcessorsWorker
    Process: com.smartnsens.opencvapp, PID: 24639
    java.lang.NullPointerException: Attempt to invoke virtual method 'int com.otaliastudios.cameraview.Size.getWidth()' on a null object reference
        at com.smartnsens.opencvapp.MainActivity$1.process(MainActivity.java:134)
        at com.otaliastudios.cameraview.CameraView$Callbacks$11.run(CameraView.java:1809)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2019-04-27 10:18:26.255 24639-24659/com.smartnsens.opencvapp D/Camera: app passed NULL surface
2019-04-27 10:18:26.501 24639-24663/com.smartnsens.opencvapp D/EGL_emulation: eglMakeCurrent: 0xa86052a0: ver 2 0 (tinfo 0xa8603380)
2019-04-27 10:18:26.793 24639-24639/com.smartnsens.opencvapp E/libEGL: call to OpenGL ES API with no current context (logged once per thread)
```

And my FrameProcessor code:

```java
        camera.addFrameProcessor(new FrameProcessor() {

            @Override
            @WorkerThread
            public void process(Frame frame) {

                // Get all the frame's data
                byte[] data = frame.getData();
                int rotation = frame.getRotation();
                long time = frame.getTime();
                Size size = frame.getSize();
                int format = frame.getFormat();

                // Preview started (first)
                if (mBitmap == null) {

                    mFrameSize = size.getWidth() * size.getHeight();
                    mRGBA = new int[mFrameSize];
                    mBitmap = Bitmap.createBitmap(size.getWidth(), size.getHeight(), Bitmap.Config.ARGB_8888);

                }

                // Process the new frame only if the previous DoPreviewFrame() has already finished
                // the last frame processing and its rendering.
                if ( !bProcessing ) {

                    int[] rgba = mRGBA;

                    // FPS counter (uses a 20frames trailing window to compute)
                    thisTime = System.currentTimeMillis();
                    mLastFramesTimes.add(thisTime);

                    // Hold the first 30 frames timestamps before start to process the frames
                    if (mLastFramesTimes.size() <= 30)
                        return;

                    // Encode the raw data frame in a Bitmap image
                    ByteArrayOutputStream out = new ByteArrayOutputStream();
                    YuvImage yuvImage = new YuvImage(data, ImageFormat.NV21, size.getWidth(), size.getHeight(), null);
                    yuvImage.compressToJpeg(new Rect(0, 0, size.getWidth(), size.getHeight()), 90, out);
                    byte[] imageBytes = out.toByteArray();
                    bmpImage = CameraUtils.decodeBitmap(imageBytes);

                    mHandler.post(DoPreviewFrame);
                }
            }
        });

    }
```

Best Regards.
Kleyson Rios.

**Comment by natario1** [comment]
@kleysonr at which line does this error happen? Have you posted your entire process() method?
