### ISSUE TITLE
Hytera PNC550(Android 8.1), video capture bug.

### ISSUE THREAD

**Issue by adaonder** [natario1/CameraView#459]
### Describe the bug
Full video recorder mode bug.

### To Reproduce
1. Click on Normal Video Capture button.
3. See error (Android 8.1 HYTERA PNC550 Device)

### Logs
com.otaliastudios.cameraview.demo E/MediaRecorder: start failed: -19

com.otaliastudios.cameraview.demo E/MediaRecorder: stop called in an invalid state: 0

com.otaliastudios.cameraview.demo W/FullVideoRecorder: stop: Error while closing media recorder. Swallowing java.lang.IllegalStateException
    java.lang.IllegalStateException
        at android.media.MediaRecorder.stop(Native Method)
        at com.otaliastudios.cameraview.FullVideoRecorder.stop(FullVideoRecorder.java:116)
        at com.otaliastudios.cameraview.FullVideoRecorder.start(FullVideoRecorder.java:108)
        at com.otaliastudios.cameraview.Camera1$14.run(Camera1.java:697)
        at com.otaliastudios.cameraview.Camera1$2.run(Camera1.java:61)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)

com.otaliastudios.cameraview.demo I/CameraCallbacks: dispatchError com.otaliastudios.cameraview.CameraException
    com.otaliastudios.cameraview.CameraException
        at com.otaliastudios.cameraview.Camera1.onVideoResult(Camera1.java:655)
        at com.otaliastudios.cameraview.VideoRecorder.dispatchResult(VideoRecorder.java:28)
        at com.otaliastudios.cameraview.FullVideoRecorder.stop(FullVideoRecorder.java:132)
        at com.otaliastudios.cameraview.FullVideoRecorder.start(FullVideoRecorder.java:108)
        at com.otaliastudios.cameraview.Camera1$14.run(Camera1.java:697)
        at com.otaliastudios.cameraview.Camera1$2.run(Camera1.java:61)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by natario1** [comment]
You can search for MediaRecorder: start failed: -19 on StackOverflow. It probably means you have set some parameters which are not accepted by the device (audio bit rate, video bit rate, video max duration... this kind of things).
