### ISSUE TITLE
NullPointerException in SnapshotVideoRecorder - engine.notify() 

### ISSUE THREAD

**Issue by adaonder** [natario1/CameraView#460]
LOG:

E/AndroidRuntime: FATAL EXCEPTION: GLThread 6076
    Process: com.idenfit.guardware, PID: 14843
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.otaliastudios.cameraview.MediaEncoderEngine.notify(java.lang.String, java.lang.Object)' on a null object reference
        at com.otaliastudios.cameraview.SnapshotVideoRecorder.onRendererFrame(SnapshotVideoRecorder.java:109)
        at com.otaliastudios.cameraview.GlCameraPreview.onDrawFrame(GlCameraPreview.java:209)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1575)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)

**Comment by wosiu** [comment]
Please provide basic information from a bug report template, at least:
- CameraView version: *version number*
- Reproducible in official demo app: *yes/no*
- Device / Android version: *Pixel, API 28*
