### ISSUE TITLE
ImageFormat Exception

### ISSUE THREAD

**Issue by brnogz** [natario1/CameraView#470]
I got crash report below from crashlytics. 

- CameraView version: 2.0.0-beta4
- Android:5.1.1
- Device Oppo a59s

### Logs
```
Fatal Exception: java.lang.IllegalArgumentException: only support ImageFormat.NV21 and ImageFormat.YUY2 for now
       at android.graphics.YuvImage.(YuvImage.java:82)
       at com.otaliastudios.cameraview.SnapshotPictureRecorder$2$1.run(SnapshotPictureRecorder.java:174)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by HBiSoft** [comment]
@brnogz I don't think it's related to the library, have a look ate this question/answer - https://stackoverflow.com/questions/11511522/byte-array-image-to-bitmap

**Comment by brnogz** [comment]
@HBiSoft I don't do any image conversion or processing.  Logs include only cameraview and android classes and YuvImage used in cameraview. Because of this, i create this issue but if it is a configuration error of mine, could you help me to solve?

**Comment by brnogz** [comment]
what a nice way to manage issues

**Comment by natario1** [comment]
This should be fixed now.
