### ISSUE TITLE
Crash on Moto G 5

### ISSUE THREAD

**Issue by orelvia** [natario1/CameraView#480]
### Crash on a Moto G5
I see a crash in Crashlytics happening on a specific device, not sure exactly when as I only see the stack trace from CameraView and not from my app

- CameraView version: 2.0.0-beta04
- Reproducible in official demo app: no
- Device / Android version: Moto G (5) Plus / 8.1.0

### Logs
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
       at com.otaliastudios.cameraview.CameraOptions.(CameraOptions.java:38)
       at com.otaliastudios.cameraview.Camera1.createCamera(Camera1.java:238)
       at com.otaliastudios.cameraview.Camera1.onStart(Camera1.java:270)
       at com.otaliastudios.cameraview.CameraController$3.run(CameraController.java:189)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by natario1** [comment]
It's impossible to know what's wrong without a proper stack trace (invoked iterator() on a null reference of what?). Feel free to reopen if you have more information (like the line number at least).
