### ISSUE TITLE
Unknow crashes

### ISSUE THREAD

**Issue by Rishabh-sx** [natario1/CameraView#485]
When ever switching application from background to foreground or while opening camera. 

USER_COMMENT=null
ANDROID_VERSION=9
APP_VERSION_NAME=1.0
BRAND=xiaomi
PHONE_MODEL=Redmi Note 5 Pro
CUSTOM_DATA=
STACK_TRACE=java.lang.RuntimeException: setParameters failed
at android.hardware.Camera.native_setParameters(Native Method)
at android.hardware.Camera.setParameters(Camera.java:2262)
at com.otaliastudios.cameraview.Camera1$19.run(Camera1.java:860)
at com.otaliastudios.cameraview.Camera1$2.run(Camera1.java:62)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:201)
at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by Rishabh-sx** [comment]
@natario1, Can you please check this issue. Otherwise I will be in big trouble.

**Comment by Rishabh-sx** [comment]
Resolved after updating dependency version
