### ISSUE TITLE
Crash when stopVideo() is called.

### ISSUE THREAD

**Issue by RAN3000** [natario1/CameraView#512]
### Describe the bug
When a video snapshot recording is stopped before the max duration (with `camera.stopVideo()`), the app crashes.

- CameraView version: 2.0.0-rc1
- Reproducible in official demo app: yes
- Device / Android version: Galaxy A5, API 24

### To Reproduce
A quick way to reproduce this, is to replace line 291 of the demo's `CameraActivity.java` with `camera.stopVideo()`.
So that you can start recording the video snapshot and stop it before the usual 5 seconds pass.

### Logs
```
2019-07-21 20:37:51.978 21072-21162/com.otaliastudios.cameraview.demo W/MediaEncoderEngine: end: Dispatching end to listener - reason: 0 error: java.lang.IllegalStateException: Failed to stop the muxer
    java.lang.IllegalStateException: Failed to stop the muxer
        at android.media.MediaMuxer.nativeStop(Native Method)
        at android.media.MediaMuxer.stop(MediaMuxer.java:271)
        at com.otaliastudios.cameraview.video.encoding.MediaEncoderEngine.end(MediaEncoderEngine.java:220)
        at com.otaliastudios.cameraview.video.encoding.MediaEncoderEngine.access$1000(MediaEncoderEngine.java:56)
        at com.otaliastudios.cameraview.video.encoding.MediaEncoderEngine$Controller.notifyStopped(MediaEncoderEngine.java:380)
        at com.otaliastudios.cameraview.video.encoding.MediaEncoder.onStopped(MediaEncoder.java:310)
        at com.otaliastudios.cameraview.video.encoding.TextureMediaEncoder.onStopped(TextureMediaEncoder.java:166)
        at com.otaliastudios.cameraview.video.encoding.MediaEncoder.drainOutput(MediaEncoder.java:466)
        at com.otaliastudios.cameraview.video.encoding.VideoMediaEncoder.onStop(VideoMediaEncoder.java:92)
        at com.otaliastudios.cameraview.video.encoding.MediaEncoder$4.run(MediaEncoder.java:257)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
2019-07-21 20:37:51.979 21072-21162/com.otaliastudios.cameraview.demo E/SnapshotVideoRecorder: Error onEncodingEnd java.lang.IllegalStateException: Failed to stop the muxer
    java.lang.IllegalStateException: Failed to stop the muxer
        at android.media.MediaMuxer.nativeStop(Native Method)
        at android.media.MediaMuxer.stop(MediaMuxer.java:271)
        at com.otaliastudios.cameraview.video.encoding.MediaEncoderEngine.end(MediaEncoderEngine.java:220)
        at com.otaliastudios.cameraview.video.encoding.MediaEncoderEngine.access$1000(MediaEncoderEngine.java:56)
        at com.otaliastudios.cameraview.video.encoding.MediaEncoderEngine$Controller.notifyStopped(MediaEncoderEngine.java:380)
        at com.otaliastudios.cameraview.video.encoding.MediaEncoder.onStopped(MediaEncoder.java:310)
        at com.otaliastudios.cameraview.video.encoding.TextureMediaEncoder.onStopped(TextureMediaEncoder.java:166)
        at com.otaliastudios.cameraview.video.encoding.MediaEncoder.drainOutput(MediaEncoder.java:466)
        at com.otaliastudios.cameraview.video.encoding.VideoMediaEncoder.onStop(VideoMediaEncoder.java:92)
        at com.otaliastudios.cameraview.video.encoding.MediaEncoder$4.run(MediaEncoder.java:257)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
2019-07-21 20:37:51.979 21072-21095/com.otaliastudios.cameraview.demo I/Camera2Engine: onImageAvailable we have both a byte buffer and an Image.
2019-07-21 20:37:51.979 21072-21095/com.otaliastudios.cameraview.demo D/gralloc: gralloc_lock_ycbcr success. format : 11, usage: 3, ycbcr.y: 0xc5363000, .cb: 0xc53ae001, .cr: 0xc53ae000, .ystride: 640 , .cstride: 640, .chroma_step: 2
2019-07-21 20:37:51.983 21072-21162/com.otaliastudios.cameraview.demo E/AndroidRuntime: FATAL EXCEPTION: VideoEncoder
    Process: com.otaliastudios.cameraview.demo, PID: 21072
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.otaliastudios.cameraview.preview.GlCameraPreview.removeRendererFrameCallback(com.otaliastudios.cameraview.preview.RendererFrameCallback)' on a null object reference
        at com.otaliastudios.cameraview.video.SnapshotVideoRecorder.onEncodingEnd(SnapshotVideoRecorder.java:243)
        at com.otaliastudios.cameraview.video.encoding.MediaEncoderEngine.end(MediaEncoderEngine.java:229)
        at com.otaliastudios.cameraview.video.encoding.MediaEncoderEngine.access$1000(MediaEncoderEngine.java:56)
        at com.otaliastudios.cameraview.video.encoding.MediaEncoderEngine$Controller.notifyStopped(MediaEncoderEngine.java:380)
        at com.otaliastudios.cameraview.video.encoding.MediaEncoder.onStopped(MediaEncoder.java:310)
        at com.otaliastudios.cameraview.video.encoding.TextureMediaEncoder.onStopped(TextureMediaEncoder.java:166)
        at com.otaliastudios.cameraview.video.encoding.MediaEncoder.drainOutput(MediaEncoder.java:466)
        at com.otaliastudios.cameraview.video.encoding.VideoMediaEncoder.onStop(VideoMediaEncoder.java:92)
        at com.otaliastudios.cameraview.video.encoding.MediaEncoder$4.run(MediaEncoder.java:257)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

Let me know if you need more logs or anything else!

**Comment by Ahmed-Adel-Ismail** [comment]
This error still persists :
library version : com.otaliastudios:cameraview:2.6.1'
what happened : I stopped the video 
stack trace : 

2020-01-16 06:40:16.146 E/MediaMuxer: stop() is called in invalid state 3
2020-01-16 06:40:16.147 E/SnapshotVideoRecorder: Error onEncodingEnd java.lang.IllegalStateException: Failed to stop the muxer
    java.lang.IllegalStateException: Failed to stop the muxer
        at android.media.MediaMuxer.nativeStop(Native Method)
        at android.media.MediaMuxer.stop(MediaMuxer.java:454)
        at com.otaliastudios.cameraview.video.encoding.MediaEncoderEngine.end(MediaEncoderEngine.java:224)
        at com.otaliastudios.cameraview.video.encoding.MediaEncoderEngine.access$1100(MediaEncoderEngine.java:57)
        at com.otaliastudios.cameraview.video.encoding.MediaEncoderEngine$Controller$3.run(MediaEncoderEngine.java:412)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:207)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2020-01-16 06:40:16.149 E/CameraEngine: onVideoResult result is null: something went wrong. java.lang.IllegalStateException: Failed to stop the muxer
    java.lang.IllegalStateException: Failed to stop the muxer
        at android.media.MediaMuxer.nativeStop(Native Method)
        at android.media.MediaMuxer.stop(MediaMuxer.java:454)
        at com.otaliastudios.cameraview.video.encoding.MediaEncoderEngine.end(MediaEncoderEngine.java:224)
        at com.otaliastudios.cameraview.video.encoding.MediaEncoderEngine.access$1100(MediaEncoderEngine.java:57)
        at com.otaliastudios.cameraview.video.encoding.MediaEncoderEngine$Controller$3.run(MediaEncoderEngine.java:412)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:207)
        at android.os.HandlerThread.run(HandlerThread.java:65)
