### ISSUE TITLE
FATAL EXCEPTION: VideoEncoder on Stopping Video Snapshot

### ISSUE THREAD

**Issue by BlindJerobine** [natario1/CameraView#518]
Hi, if I try to end a VideoSnapshot with .stopVideo() I get following error:

E/AndroidRuntime: FATAL EXCEPTION: VideoEncoder
    Process: xxx, PID: 23287
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.otaliastudios.cameraview.preview.GlCameraPreview.removeRendererFrameCallback(com.otaliastudios.cameraview.preview.RendererFrameCallback)' on a null object reference
        at com.otaliastudios.cameraview.video.SnapshotVideoRecorder.onEncodingEnd(SnapshotVideoRecorder.java:243)
        at com.otaliastudios.cameraview.video.encoding.MediaEncoderEngine.end(MediaEncoderEngine.java:229)
        at com.otaliastudios.cameraview.video.encoding.MediaEncoderEngine.access$1000(MediaEncoderEngine.java:56)
        at com.otaliastudios.cameraview.video.encoding.MediaEncoderEngine$Controller.notifyStopped(MediaEncoderEngine.java:380)
        at com.otaliastudios.cameraview.video.encoding.MediaEncoder.onStopped(MediaEncoder.java:310)
        at com.otaliastudios.cameraview.video.encoding.TextureMediaEncoder.onStopped(TextureMediaEncoder.java:166)
        at com.otaliastudios.cameraview.video.encoding.MediaEncoder.drainOutput(MediaEncoder.java:466)
        at com.otaliastudios.cameraview.video.encoding.VideoMediaEncoder.onStop(VideoMediaEncoder.java:92)
        at com.otaliastudios.cameraview.video.encoding.MediaEncoder$4.run(MediaEncoder.java:257)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)

If the VideoSnapshot ends because of a time limit, it works.

- CameraView version: 2.0.0rc1
- Reproducible in official demo app: no
- Device / Android version: Pixel 2XL, Android 9

**Comment by natario1** [comment]
See #512
