### ISSUE TITLE
Video Snapshot crash when closing app while recording

### ISSUE THREAD

**Issue by sceneren** [natario1/CameraView#526]
### Describe the bug
use camera.takeVideoSnapshot() after,click HOME to background  and restart APP ,crashed

- CameraView version: 2.0.0-rc2
- Reproducible in official demo app: yes
- Device / Android version: Google Pixel XL Android 9, API 28

###Log:
2019-07-30 17:03:57.582 3189-3265/com.agz.testvideorecord E/GLConsumer: [SurfaceTexture-2-3189-1] checkAndUpdateEglState: invalid current EGLContext
2019-07-30 17:03:57.602 3189-3265/com.agz.testvideorecord E/AndroidRuntime: FATAL EXCEPTION: GLThread 2856
    Process: com.agz.testvideorecord, PID: 3189
    java.lang.IllegalStateException: Unable to update texture contents (see logcat for details)
        at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
        at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:243)
        at com.otaliastudios.cameraview.video.SnapshotVideoRecorder.onRendererFrame(SnapshotVideoRecorder.java:181)
        at com.otaliastudios.cameraview.preview.GlCameraPreview$Renderer.onDrawFrame(GlCameraPreview.java:212)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1571)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
2019-07-30 17:03:57.848 3189-3189/com.agz.testvideorecord E/libEGL: call to OpenGL ES API with no current context (logged once per thread)

**Comment by natario1** [comment]
You press home while recording the video? Or what?

**Comment by sceneren** [comment]
yes,when I recoding video ,click Home

**Comment by sceneren** [comment]
When to update Gradle dependencies？Fix #526,#514

**Comment by natario1** [comment]
@sceneren you can Watch this repository so you'll get notifications when we have new releases.

**Comment by sceneren** [comment]
@natario1 thx
