### ISSUE TITLE
Frame.getSize returns null

### ISSUE THREAD

**Issue by KanwarpartapSinghBimrah** [natario1/CameraView#544]
See screenshot what code I had written. I got only one error like this 

**java.lang.IllegalStateException: frame.size must not be null**
```
FATAL EXCEPTION: FrameProcessorsWorker
Process: com.royalbimrah.ai, PID: 12887
java.lang.IllegalStateException: frame.size must not be null
  at com.royalbimrah.ai.facedetection.FaceDetectionActivity.process(FaceDetectionActivity.kt:67)
  at com.otaliastudios.cameraview.CameraView$Callbacks$13.run(CameraView.java:1742)
  at android.os.Handler.handleCallback(Handler.java:751)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:154)
  at android.os.HandlerThread.run(HandlerThread.java:61)
```

Also, you can see code and let me know how to solve this error soon.

![image](https://user-images.githubusercontent.com/39325207/62851469-c50c9b00-bd03-11e9-8fed-b14053b82165.png)

**Comment by natario1** [comment]
@KanwarpartapSinghBimrah are you using Camera1 or Camera2 engine?

Can you enable logs in your app (`CameraLogger.setLogLevel(VERBOSE)`) and paste them here?

**Comment by natario1** [comment]
OK, I can see this issue with Camera2... I would like to know if you're using Camera1 or Camera2. If you are using Camera1, please post logs as well!
