### ISSUE TITLE
Exception occurs while taking a video on Xiaomi MI A1, Android Pie

### ISSUE THREAD

**Issue by zauli83** [natario1/CameraView#578]
Cannot take video, exception occurs
- CameraView version: 2.2.0
- Camera engine used: both
- Reproducible in official demo app: no
- Device / Android version: Xiaomi Mi A1, Android Pie

### To Reproduce
1) Take a video

### XML layout
```
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        xmlns:tools="http://schemas.android.com/tools"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        tools:context=".record.RecordVideoActivity">

    <com.otaliastudios.cameraview.CameraView
            android:id="@+id/camera"
            android:layout_width="0dp"
            android:layout_height="0dp"
            android:keepScreenOn="true"
            app:cameraGestureTap="none"
            app:cameraGestureLongTap="none"
            app:cameraGesturePinch="zoom"
            app:cameraGestureScrollHorizontal="none"
            app:cameraGestureScrollVertical="none"
            app:cameraFacing="back"
            app:cameraMode="video"
            app:cameraAudio="on"
            app:cameraPlaySounds="true"
            app:cameraUseDeviceOrientation="true"
            app:layout_constraintTop_toTopOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintBottom_toBottomOf="parent">

    </com.otaliastudios.cameraview.CameraView>

    <Button
            android:id="@+id/start"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="START"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintStart_toStartOf="parent" />

    <Button
            android:id="@+id/stop"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="STOP"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent" />

</androidx.constraintlayout.widget.ConstraintLayout>

```

Code:

```
class RecordVideoActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_record_video)
        CameraLogger.setLogLevel(CameraLogger.LEVEL_VERBOSE)

        camera.setLifecycleOwner(this)
        camera.addCameraListener(object : CameraListener() {
            override fun onVideoTaken(result: VideoResult) {
                super.onVideoTaken(result)
            }

            override fun onCameraError(exception: CameraException) {
                super.onCameraError(exception)
                Log.e(TAG, "Error", exception)
            }
        })

        start.setOnClickListener { _ ->
            camera.takeVideo(
                File(
                    Environment.getExternalStorageDirectory().toString()
                            + File.separator +
                            Constant.DEFAULTFOLDER + File.separator + "${Date()}.mp4"
                )
            )
        }

        stop.setOnClickListener {
            camera.stopVideo()
        }
    }

    companion object {
        val TAG = RecordVideoActivity::class.java.simpleName
    }


}
```

### Logs
19-09-04 09:31:35.906 26699-26780/xxxxx V/Frame: Frame with time 1567582295905 is being released.
2019-09-04 09:31:35.950 26699-26699/xxxxx V/CameraEngine: takeVideo scheduling
2019-09-04 09:31:35.951 26699-26780/xxxxx V/CameraEngine: takeVideo performing. BindState: 2 isTakingVideo: false
2019-09-04 09:31:36.078 26699-26780/xxxxx W/VideoCapabilities: Unrecognized profile 4 for video/hevc
2019-09-04 09:31:36.082 26699-26780/xxxxx W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
2019-09-04 09:31:36.088 26699-26780/xxxxx W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
2019-09-04 09:31:36.146 26699-26780/xxxxx I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
2019-09-04 09:31:36.151 26699-26780/xxxxx W/Utils: could not parse long range '175-174'
2019-09-04 09:31:36.163 26699-26780/xxxxx I/DeviceEncoders: findDeviceEncoder - type: video/avc encoders: 2
2019-09-04 09:31:36.163 26699-26780/xxxxx I/DeviceEncoders: Enabled. Found video encoder: OMX.qcom.video.encoder.avc
2019-09-04 09:31:36.164 26699-26780/xxxxx I/DeviceEncoders: findDeviceEncoder - type: audio/mp4a-latm encoders: 1
2019-09-04 09:31:36.165 26699-26780/xxxxx I/DeviceEncoders: Enabled. Found audio encoder: OMX.google.aac.encoder
2019-09-04 09:31:36.165 26699-26780/xxxxx I/DeviceEncoders: getSupportedVideoSize - inputSize: 4096x2160 adjustedSize: 3840x2024
2019-09-04 09:31:36.166 26699-26780/xxxxx I/DeviceEncoders: getSupportedVideoBitRate - inputRate: 42000000 adjustedRate: 42000000
2019-09-04 09:31:36.166 26699-26780/xxxxx I/DeviceEncoders: getSupportedAudioBitRate - inputRate: 156000 adjustedRate: 156000
2019-09-04 09:31:36.166 26699-26780/xxxxx I/DeviceEncoders: getSupportedVideoFrameRate - inputRate: 30 adjustedRate: 30
2019-09-04 09:31:36.257 26699-26780/xxxxx E/MediaRecorder: start failed: -19
2019-09-04 09:31:36.259 26699-26780/xxxxx W/FullVideoRecorder: start: Error while starting media recorder. java.lang.RuntimeException: start failed.
    java.lang.RuntimeException: start failed.
        at android.media.MediaRecorder.start(Native Method)
        at com.otaliastudios.cameraview.video.FullVideoRecorder.onStart(FullVideoRecorder.java:177)
        at com.otaliastudios.cameraview.video.VideoRecorder.start(VideoRecorder.java:62)
        at com.otaliastudios.cameraview.engine.Camera1Engine.onTakeVideo(Camera1Engine.java:339)
        at com.otaliastudios.cameraview.engine.CameraEngine$23.run(CameraEngine.java:1151)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2019-09-04 09:31:36.259 26699-26780/xxxxx I/CameraCallbacks: dispatchOnVideoRecordingEnd
2019-09-04 09:31:36.260 26699-26780/xxxxx E/MediaRecorder: stop called in an invalid state: 0
2019-09-04 09:31:36.261 26699-26780/xxxxx W/FullVideoRecorder: stop: Error while closing media recorder. java.lang.IllegalStateException
    java.lang.IllegalStateException
        at android.media.MediaRecorder.stop(Native Method)
        at com.otaliastudios.cameraview.video.FullVideoRecorder.onStop(FullVideoRecorder.java:192)
        at com.otaliastudios.cameraview.video.VideoRecorder.stop(VideoRecorder.java:70)
        at com.otaliastudios.cameraview.video.FullVideoRecorder.onStart(FullVideoRecorder.java:183)
        at com.otaliastudios.cameraview.video.VideoRecorder.start(VideoRecorder.java:62)
        at com.otaliastudios.cameraview.engine.Camera1Engine.onTakeVideo(Camera1Engine.java:339)
        at com.otaliastudios.cameraview.engine.CameraEngine$23.run(CameraEngine.java:1151)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2019-09-04 09:31:36.264 26699-26780/xxxxx E/CameraEngine: onVideoResult result is null: something went wrong. java.lang.RuntimeException: start failed.
    java.lang.RuntimeException: start failed.
        at android.media.MediaRecorder.start(Native Method)
        at com.otaliastudios.cameraview.video.FullVideoRecorder.onStart(FullVideoRecorder.java:177)
        at com.otaliastudios.cameraview.video.VideoRecorder.start(VideoRecorder.java:62)
        at com.otaliastudios.cameraview.engine.Camera1Engine.onTakeVideo(Camera1Engine.java:339)
        at com.otaliastudios.cameraview.engine.CameraEngine$23.run(CameraEngine.java:1151)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2019-09-04 09:31:36.266 26699-26780/xxxxx I/CameraCallbacks: dispatchError com.otaliastudios.cameraview.CameraException: java.lang.RuntimeException: start failed.
    com.otaliastudios.cameraview.CameraException: java.lang.RuntimeException: start failed.
        at com.otaliastudios.cameraview.engine.CameraEngine.onVideoResult(CameraEngine.java:1211)
        at com.otaliastudios.cameraview.engine.Camera1Engine.onVideoResult(Camera1Engine.java:379)
        at com.otaliastudios.cameraview.video.VideoRecorder.dispatchResult(VideoRecorder.java:93)
        at com.otaliastudios.cameraview.video.Full1VideoRecorder.dispatchResult(Full1VideoRecorder.java:51)
        at com.otaliastudios.cameraview.video.FullVideoRecorder.onStop(FullVideoRecorder.java:206)
        at com.otaliastudios.cameraview.video.VideoRecorder.stop(VideoRecorder.java:70)
        at com.otaliastudios.cameraview.video.FullVideoRecorder.onStart(FullVideoRecorder.java:183)
        at com.otaliastudios.cameraview.video.VideoRecorder.start(VideoRecorder.java:62)
        at com.otaliastudios.cameraview.engine.Camera1Engine.onTakeVideo(Camera1Engine.java:339)
        at com.otaliastudios.cameraview.engine.CameraEngine$23.run(CameraEngine.java:1151)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: java.lang.RuntimeException: start failed.
        at android.media.MediaRecorder.start(Native Method)
        at com.otaliastudios.cameraview.video.FullVideoRecorder.onStart(FullVideoRecorder.java:177)
        at com.otaliastudios.cameraview.video.VideoRecorder.start(VideoRecorder.java:62) 
        at com.otaliastudios.cameraview.engine.Camera1Engine.onTakeVideo(Camera1Engine.java:339) 
        at com.otaliastudios.cameraview.engine.CameraEngine$23.run(CameraEngine.java:1151) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
2019-09-04 09:31:36.267 26699-26780/xxxxx V/FrameManager: getFrame for time: 1567582296267 RECYCLING.
2019-09-04 09:31:36.267 26699-26780/xxxxx V/CameraCallbacks: dispatchFrame: 1567582296267 processors: 0
2019-09-04 09:31:36.267 26699-26780/xxxxx V/Frame: Frame with time 1567582296267 is being released.
2019-09-04 09:31:36.268 26699-26699/xxxxx E/RecordVideoActivity: Error
    com.otaliastudios.cameraview.CameraException: java.lang.RuntimeException: start failed.
        at com.otaliastudios.cameraview.engine.CameraEngine.onVideoResult(CameraEngine.java:1211)
        at com.otaliastudios.cameraview.engine.Camera1Engine.onVideoResult(Camera1Engine.java:379)
        at com.otaliastudios.cameraview.video.VideoRecorder.dispatchResult(VideoRecorder.java:93)
        at com.otaliastudios.cameraview.video.Full1VideoRecorder.dispatchResult(Full1VideoRecorder.java:51)
        at com.otaliastudios.cameraview.video.FullVideoRecorder.onStop(FullVideoRecorder.java:206)
        at com.otaliastudios.cameraview.video.VideoRecorder.stop(VideoRecorder.java:70)
        at com.otaliastudios.cameraview.video.FullVideoRecorder.onStart(FullVideoRecorder.java:183)
        at com.otaliastudios.cameraview.video.VideoRecorder.start(VideoRecorder.java:62)
        at com.otaliastudios.cameraview.engine.Camera1Engine.onTakeVideo(Camera1Engine.java:339)
        at com.otaliastudios.cameraview.engine.CameraEngine$23.run(CameraEngine.java:1151)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: java.lang.RuntimeException: start failed.
        at android.media.MediaRecorder.start(Native Method)
        at com.otaliastudios.cameraview.video.FullVideoRecorder.onStart(FullVideoRecorder.java:177)
        at com.otaliastudios.cameraview.video.VideoRecorder.start(VideoRecorder.java:62) 
        at com.otaliastudios.cameraview.engine.Camera1Engine.onTakeVideo(Camera1Engine.java:339) 
        at com.otaliastudios.cameraview.engine.CameraEngine$23.run(CameraEngine.java:1151) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by natario1** [comment]
You might be missing storage permissions. Try defining your output File like the demo app does.

**Comment by zauli83** [comment]
It doesn't work. I've defined the output video as  File(filesDir, "video.mp4") ( as the demo does), i've also checked the permissions, but doesn't work. Same exception here.

**Comment by natario1** [comment]
But you say that this does not happen in the demo app. So I recommend trying to spot the difference that makes this crash in your app.
