### ISSUE TITLE
Camera2 Api timing issue when adding frame processors in onCameraOpened callback

### ISSUE THREAD

**Issue by cneuwirt** [natario1/CameraView#590]
### Describe the bug
An exception generally occurs when creating a CameraView with Camera2Engine that has a FrameProcessor adding in the CameraListener.onCameraOpended callback
- CameraView version: 2.2.0
- Camera engine used: camera2
- Reproducible in official demo app: no, but probably could be
- Device / Android version: Moto G7 Power Pie

The exception usually occurs when the phone wakes up after sleeping and the app tries to create a new CameraView with Camera2Engine.  Here is the stack trace of the error

**NOTE:  The error does not seem to occur when adding the FrameProcessor outside the CameraListener.onCameraOpended callback.**

E/CameraEngine: uncaughtException: Unexpected exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.otaliastudios.cameraview.size.Size.getHeight()' on a null object reference
    java.lang.NullPointerException: Attempt to invoke virtual method 'int com.otaliastudios.cameraview.size.Size.getHeight()' on a null object reference
        at com.otaliastudios.cameraview.frame.FrameManager.setUp(FrameManager.java:116)
        at com.otaliastudios.cameraview.engine.Camera2Engine.onStartPreview(Camera2Engine.java:501)
        at com.otaliastudios.cameraview.engine.CameraEngine$10.call(CameraEngine.java:511)
        at com.otaliastudios.cameraview.engine.CameraEngine$10.call(CameraEngine.java:508)
        at com.otaliastudios.cameraview.engine.Step$2.then(Step.java:115)
        at com.otaliastudios.cameraview.engine.Step$2.then(Step.java:110)
        at com.google.android.gms.tasks.zzf.run(Unknown Source:2)
        at com.otaliastudios.cameraview.internal.utils.WorkerHandler.run(WorkerHandler.java:126)
        at com.otaliastudios.cameraview.internal.utils.WorkerHandler$1.execute(WorkerHandler.java:101)
        at com.google.android.gms.tasks.zze.onComplete(Unknown Source:6)
        at com.google.android.gms.tasks.zzr.zza(Unknown Source:19)
        at com.google.android.gms.tasks.zzu.zze(Unknown Source:132)
        at com.google.android.gms.tasks.zzu.continueWithTask(Unknown Source:74)
        at com.otaliastudios.cameraview.engine.Step.doStart(Step.java:110)
        at com.otaliastudios.cameraview.engine.Step.doStart(Step.java:105)
        at com.otaliastudios.cameraview.engine.CameraEngine.startPreview(CameraEngine.java:508)
        at com.otaliastudios.cameraview.engine.CameraEngine.access$400(CameraEngine.java:119)
        at com.otaliastudios.cameraview.engine.CameraEngine$17$1$1.then(CameraEngine.java:714)
        at com.otaliastudios.cameraview.engine.CameraEngine$17$1$1.then(CameraEngine.java:710)
        at com.google.android.gms.tasks.zzp.run(Unknown Source:2)
        at com.otaliastudios.cameraview.internal.utils.WorkerHandler.run(WorkerHandler.java:126)
        at com.otaliastudios.cameraview.internal.utils.WorkerHandler$1.execute(WorkerHandler.java:101)
        at com.google.android.gms.tasks.zzo.onComplete(Unknown Source:6)
        at com.google.android.gms.tasks.zzr.zza(Unknown Source:19)
        at com.google.android.gms.tasks.zzu.setResult(Unknown Source:86)
        at com.google.android.gms.tasks.zzo.onSuccess(Unknown Source:9)
        at com.google.android.gms.tasks.zzn.run(Unknown Source:4)
        at com.google.android.gms.tasks.zzt.execute(Unknown Source:2)
        at com.google.android.gms.tasks.zzm.onComplete(Unknown Source:11)
        at com.google.android.gms.tasks.zzr.zza(Unknown Source:19)
        at com.google.android.gms.tasks.zzu.setResult(Unknown Source:86)
        at com.google.android.gms.tasks.zzo.onSuccess(Unknown Source:9)
        at com.google.android.gms.tasks.zzn.run(Unknown Source:4)
        at com.google.android.gms.tasks.zzt.execute(Unknown Source:2)
        at com.google.android.gms.tasks.zzm.onComplete(Unknown Source:11)
        at com.google.android.gms.tasks.zzr.zza(Unknown Source:19)
        at com.google.android.gms.tasks.zzu.zze(Unknown Source:132)
        at com.google.android.gms.tasks.zzu.addOnSuccessListener(Unknown Source:32)
        at com.google.android.gms.tasks.zzp.run(Unknown Source:18)
        at com.otaliastudios.cameraview.internal.utils.WorkerHandler.run(WorkerHandler.java:126)
        at com.otaliastudios.cameraview.internal.utils.WorkerHandler$1.execute(WorkerHandler.java:101)
        at com.google.android.gms.tasks.zzo.onComplete(Unknown Source:6)
        at com.google.android.gms.tasks.zzr.zza(Unknown Source:19)
        at com.google.android.gms.tasks.zzu.setResult(Unknown Source:86)
        at com.google.android.gms.tasks.zze.onSuccess(Unknown Source:8)
        at com.google.android.gms.tasks.zzn.run(Unknown Source:4)
        at com.google.android.gms.tasks.zzt.execute(Unknown Source:2)
        at com.google.android.gms.tasks.zzm.onComplete(Unknown Source:11)
        at com.google.android.gms.tasks.zzr.zza(Unknown Source:19)
        at com.google.android.gms.tasks.zzu.trySetResult(Unknown Source:94)
        at com.google.android.gms.tasks.TaskCompletionSource.trySetResult(Unknown Source:10)
        at com.otaliastudios.cameraview.engine.Camera2Engine$4.onConfigured(Camera2Engine.java:472)
        at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.lambda$onConfigured$0(CallbackProxies.java:53)
        at android.hardware.camera2.impl.-$$Lambda$CallbackProxies$SessionStateCallbackProxy$soW0qC12Osypoky6AfL3P2-TeDw.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by natario1** [comment]
Hey @cneuwirt if you can reproduce this consistently could you enable `LEVEL_INFO` logs in your app and send logs here? I was not able to reproduce this.

`CameraLogger.setLogLevel(CameraLogger.LEVEL_INFO)`

**Comment by cneuwirt** [comment]
I set the level to INFO like you asked.  The following is the log

I/CameraView: onMeasure: requested dimensions are (720[EXACTLY]x497[EXACTLY])
I/CameraView: onMeasure: previewSize is (720.0x960.0)
    onMeasure: both are MATCH_PARENT or fixed value. We adapt. This means CROP_CENTER. (720x497)
    onMeasure: requested dimensions are (720[EXACTLY]x497[EXACTLY])
    onMeasure: previewSize is (720.0x960.0)
    onMeasure: both are MATCH_PARENT or fixed value. We adapt. This means CROP_CENTER. (720x497)
    onMeasure: requested dimensions are (720[EXACTLY]x497[EXACTLY])
    onMeasure: previewSize is (720.0x960.0)
    onMeasure: both are MATCH_PARENT or fixed value. We adapt. This means CROP_CENTER. (720x497)
    onMeasure: requested dimensions are (720[EXACTLY]x497[EXACTLY])
    onMeasure: previewSize is (720.0x960.0)
    onMeasure: both are MATCH_PARENT or fixed value. We adapt. This means CROP_CENTER. (720x497)
I/CameraView: onMeasure: requested dimensions are (720[EXACTLY]x497[EXACTLY])
    onMeasure: previewSize is (720.0x960.0)
    onMeasure: both are MATCH_PARENT or fixed value. We adapt. This means CROP_CENTER. (720x497)
    onMeasure: requested dimensions are (720[EXACTLY]x497[EXACTLY])
    onMeasure: previewSize is (720.0x960.0)
    onMeasure: both are MATCH_PARENT or fixed value. We adapt. This means CROP_CENTER. (720x497)
    onMeasure: requested dimensions are (720[EXACTLY]x497[EXACTLY])
    onMeasure: previewSize is (720.0x960.0)
I/CameraView: onMeasure: both are MATCH_PARENT or fixed value. We adapt. This means CROP_CENTER. (720x497)
    onMeasure: requested dimensions are (720[EXACTLY]x497[EXACTLY])
    onMeasure: previewSize is (720.0x960.0)
    onMeasure: both are MATCH_PARENT or fixed value. We adapt. This means CROP_CENTER. (720x497)
    onMeasure: requested dimensions are (720[EXACTLY]x497[EXACTLY])
    onMeasure: previewSize is (720.0x960.0)
    onMeasure: both are MATCH_PARENT or fixed value. We adapt. This means CROP_CENTER. (720x497)
I/CameraView: onMeasure: requested dimensions are (720[EXACTLY]x497[EXACTLY])
    onMeasure: previewSize is (720.0x960.0)
    onMeasure: both are MATCH_PARENT or fixed value. We adapt. This means CROP_CENTER. (720x497)
    onMeasure: requested dimensions are (720[EXACTLY]x497[EXACTLY])
    onMeasure: previewSize is (720.0x960.0)
    onMeasure: both are MATCH_PARENT or fixed value. We adapt. This means CROP_CENTER. (720x497)
    onMeasure: requested dimensions are (720[EXACTLY]x497[EXACTLY])
    onMeasure: previewSize is (720.0x960.0)
    onMeasure: both are MATCH_PARENT or fixed value. We adapt. This means CROP_CENTER. (720x497)
I/CameraView: onMeasure: requested dimensions are (720[EXACTLY]x497[EXACTLY])
    onMeasure: previewSize is (720.0x960.0)
    onMeasure: both are MATCH_PARENT or fixed value. We adapt. This means CROP_CENTER. (720x497)
    onMeasure: requested dimensions are (720[EXACTLY]x497[EXACTLY])
    onMeasure: previewSize is (720.0x960.0)
    onMeasure: both are MATCH_PARENT or fixed value. We adapt. This means CROP_CENTER. (720x497)
    onMeasure: requested dimensions are (720[EXACTLY]x497[EXACTLY])
    onMeasure: previewSize is (720.0x960.0)
    onMeasure: both are MATCH_PARENT or fixed value. We adapt. This means CROP_CENTER. (720x497)
I/CameraView: onMeasure: requested dimensions are (720[EXACTLY]x497[EXACTLY])
    onMeasure: previewSize is (720.0x960.0)
    onMeasure: both are MATCH_PARENT or fixed value. We adapt. This means CROP_CENTER. (720x497)
I/CameraEngine: destroy: state: ENGINE_STATE_STARTED thread: Thread[main,5,main]
    Stop: posting runnable. State: ENGINE_STATE_STARTED
W/CameraEngine: Stop: executing runnable. AllState is 0
I/Step: ALL doStop Called. Enqueuing.
    ALL doStop About to stop. Setting state to STOPPING
I/CameraEngine: stopPreview needsStopPreview: true swallowExceptions: true
I/Step: PREVIEW doStop Called. Enqueuing.
    PREVIEW doStop About to stop. Setting state to STOPPING
I/Camera2Engine: onStopPreview: About to clean up.
W/FrameManager: release called twice. Ignoring.
I/Camera2Engine: onStopPreview: Returning.
I/Step: PREVIEW doStop Succeeded! Setting state to STOPPED
    BIND doStop Called. Enqueuing.
    BIND doStop About to stop. Setting state to STOPPING
I/Camera2Engine: onStopBind: About to clean up.
    onStopBind: Returning.
I/Step: BIND doStop Succeeded! Setting state to STOPPED
    ENGINE doStop Called. Enqueuing.
    ENGINE doStop About to stop. Setting state to STOPPING
I/Camera2Engine: onStopEngine: About to clean up.
    onStopEngine: Clean up. Releasing camera.
I/Camera2Engine: onStopEngine: Clean up. Released camera.
W/Camera2Engine: onStopEngine: Returning.
I/Step: ENGINE doStop Succeeded! Setting state to STOPPED
I/CameraCallbacks: dispatchOnCameraClosed
I/Step: ALL doStop Succeeded! Setting state to STOPPED
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sftp.accesscontrol, PID: 18945
    java.lang.NullPointerException: Attempt to invoke virtual method 'int com.otaliastudios.cameraview.size.Size.getHeight()' on a null object reference
        at com.otaliastudios.cameraview.frame.FrameManager.setUp(FrameManager.java:116)
        at com.otaliastudios.cameraview.engine.Camera2Engine.onStartPreview(Camera2Engine.java:501)
        at com.otaliastudios.cameraview.engine.CameraEngine$10.call(CameraEngine.java:511)
        at com.otaliastudios.cameraview.engine.CameraEngine$10.call(CameraEngine.java:508)
        at com.otaliastudios.cameraview.engine.Step$2.then(Step.java:115)
        at com.otaliastudios.cameraview.engine.Step$2.then(Step.java:110)
        at com.google.android.gms.tasks.zzf.run(Unknown Source:2)
        at com.otaliastudios.cameraview.internal.utils.WorkerHandler.run(WorkerHandler.java:126)
        at com.otaliastudios.cameraview.internal.utils.WorkerHandler$1.execute(WorkerHandler.java:101)
        at com.google.android.gms.tasks.zze.onComplete(Unknown Source:6)
        at com.google.android.gms.tasks.zzr.zza(Unknown Source:19)
        at com.google.android.gms.tasks.zzu.zze(Unknown Source:132)
        at com.google.android.gms.tasks.zzu.continueWithTask(Unknown Source:74)
        at com.otaliastudios.cameraview.engine.Step.doStart(Step.java:110)
        at com.otaliastudios.cameraview.engine.Step.doStart(Step.java:105)
        at com.otaliastudios.cameraview.engine.CameraEngine.startPreview(CameraEngine.java:508)
        at com.otaliastudios.cameraview.engine.CameraEngine.access$400(CameraEngine.java:119)
        at com.otaliastudios.cameraview.engine.CameraEngine$17$1$1.then(CameraEngine.java:714)
        at com.otaliastudios.cameraview.engine.CameraEngine$17$1$1.then(CameraEngine.java:710)
        at com.google.android.gms.tasks.zzp.run(Unknown Source:2)
        at com.otaliastudios.cameraview.internal.utils.WorkerHandler.run(WorkerHandler.java:126)
        at com.otaliastudios.cameraview.internal.utils.WorkerHandler$1.execute(WorkerHandler.java:101)
        at com.google.android.gms.tasks.zzo.onComplete(Unknown Source:6)
        at com.google.android.gms.tasks.zzr.zza(Unknown Source:19)
        at com.google.android.gms.tasks.zzu.setResult(Unknown Source:86)
        at com.google.android.gms.tasks.zzo.onSuccess(Unknown Source:9)
        at com.google.android.gms.tasks.zzn.run(Unknown Source:4)
        at com.google.android.gms.tasks.zzt.execute(Unknown Source:2)
        at com.google.android.gms.tasks.zzm.onComplete(Unknown Source:11)
        at com.google.android.gms.tasks.zzr.zza(Unknown Source:19)
        at com.google.android.gms.tasks.zzu.setResult(Unknown Source:86)
        at com.google.android.gms.tasks.zzo.onSuccess(Unknown Source:9)
        at com.google.android.gms.tasks.zzn.run(Unknown Source:4)
        at com.google.android.gms.tasks.zzt.execute(Unknown Source:2)
        at com.google.android.gms.tasks.zzm.onComplete(Unknown Source:11)
        at com.google.android.gms.tasks.zzr.zza(Unknown Source:19)
        at com.google.android.gms.tasks.zzu.zze(Unknown Source:132)
        at com.google.android.gms.tasks.zzu.addOnSuccessListener(Unknown Source:32)
        at com.google.android.gms.tasks.zzp.run(Unknown Source:18)
        at com.otaliastudios.cameraview.internal.utils.WorkerHandler.run(WorkerHandler.java:126)
        at com.otaliastudios.cameraview.internal.utils.WorkerHandler$1.execute(WorkerHandler.java:101)
        at com.google.android.gms.tasks.zzo.onComplete(Unknown Source:6)
        at com.google.android.gms.tasks.zzr.zza(Unknown Source:19)
        at com.google.android.gms.tasks.zzu.setResult(Unknown Source:86)
        at com.google.android.gms.tasks.zze.onSuccess(Unknown Source:8)
        at com.google.android.gms.tasks.zzn.run(Unknown Source:4)
        at com.google.android.gms.tasks.zzt.execute(Unknown Source:2)
        at com.google.android.gms.tasks.zzm.onComplete(Unknown Source:11)
        at com.google.android.gms.tasks.zzr.zza(Unknown Source:19)
        at com.google.android.gms.tasks.zzu.trySetResult(Unknown Source:94)
        at com.google.android.gms.tasks.TaskCompletionSource.trySetResult(Unknown Source:10)
        at com.otaliastudios.cameraview.engine.Camera2Engine$4.onConfigured(Camera2Engine.java:472)
        at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.lambda$onConfigured$0(CallbackProxies.java:53)
        at android.hardware.camera2.impl.-$$Lambda$CallbackProxies$SessionStateCallbackProxy$soW0qC12Osypoky6AfL3P2-TeDw.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
I/Process: Sending signal. PID: 18945 SIG: 9
Process 18945 terminated.

**Comment by natario1** [comment]
Thanks @cneuwirt , any chance you could paste logs from when the app starts (I mean, from when the fragment / activity containing a `CameraView` starts) up to the crash?

In the logs above the camera has already encountered the issue and is just destroying itself before crashing, so we can't see the interesting part.

**Comment by cneuwirt** [comment]
Still trying to get this info.  It seems to happen after camera sleeps, wakes up and I open new cameraView.  Haven’t been able to catch it at the right moment but will get it sooner or later.

Do you or any of your users notice camera2 frame processing with mobile
Vision for example is much worse than Camera1?  Camera1 frames seem to detect barcodes much better
