### ISSUE TITLE
Crashes after using setLocation api

### ISSUE THREAD

**Issue by natario1** [natario1/CameraView#6]
Experiencing some crashes when moving to front camera on some devices, due to the infamous native error `setParameters() failed`.

```
java.lang.RuntimeException: setParameters failed
at android.hardware.Camera.native_setParameters(Native Method)
at android.hardware.Camera.setParameters(Camera.java:1884)
at com.otaliastudios.cameraview.Camera1.start(Camera1.java:148)
at com.otaliastudios.cameraview.Camera1.setFacing(Camera1.java:245)
at com.otaliastudios.cameraview.CameraView$3.run(CameraView.java:755)
```

**Comment by natario1** [comment]
I think this happens after using `setLocation`. That somehow is rejected by `Camera.Parameters` and further use of that parameters make the app crash in future calls. I'm not sure what to do here
