### ISSUE TITLE
Unable to record videos on my device

### ISSUE THREAD

**Issue by Vitor238** [natario1/CameraView#600]
### Describe the bug
When trying to record a video the app crashes. In demo app doesn't work using camera.1 In my app doesn't work using camera 2.

- CameraView version: 'com.otaliastudios:cameraview:2.2.0'
- Camera engine used: *both*
- Reproducible in official demo app: *yes*
- Device / Android version: *LG K10 Power, API 24*

### To Reproduce
Steps to reproduce the behavior, possibly in the demo app:
1.Go to the settings menu and change the mode to video
2. Go to the settings menu and change the engine to camera2
3. Click to start recording a video and the app will crash

### Expected behavior
Record videos without crashes.

### XML layout

```xml
        <com.otaliastudios.cameraview.CameraView
            android:id="@+id/cameraView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:keepScreenOn="true"
            app:cameraGestureLongTap="takePicture"
            app:cameraGesturePinch="zoom"
            app:cameraGestureScrollVertical="exposureCorrection"
            app:cameraGestureTap="autoFocus"
            app:cameraPlaySounds="false"
            app:cameraEngine="camera2"
            app:cameraMode="picture"
            app:cameraAudio="stereo">
        </com.otaliastudios.cameraview.CameraView>
```

### Logs
2019-09-26 13:20:48.834 26030-26135/cameraapp.cameraapp.com.cameraapp E/Camera: Unknown message type 536870912
2019-09-26 13:20:50.088 26030-26135/cameraapp.cameraapp.com.cameraapp D/Camera: app passed NULL surface
2019-09-26 13:20:50.682 26030-26135/cameraapp.cameraapp.com.cameraapp V/MediaRecorder: setCamera(0x8e683fa0,0xa78aefc0)
2019-09-26 13:20:51.099 26030-26135/cameraapp.cameraapp.com.cameraapp E/CameraEngine: uncaughtException: Unexpected exception: java.lang.RuntimeException: Size not supported for unknown reason. Might be an aspect ratio issue. Desired size:1920x1088
    java.lang.RuntimeException: Size not supported for unknown reason. Might be an aspect ratio issue. Desired size:1920x1088
        at com.otaliastudios.cameraview.internal.DeviceEncoders.getSupportedVideoSize(DeviceEncoders.java:214)
        at com.otaliastudios.cameraview.video.FullVideoRecorder.onPrepareMediaRecorder(FullVideoRecorder.java:100)
        at com.otaliastudios.cameraview.video.Full1VideoRecorder.onPrepareMediaRecorder(Full1VideoRecorder.java:44)
        at com.otaliastudios.cameraview.video.FullVideoRecorder.prepareMediaRecorder(FullVideoRecorder.java:45)
        at com.otaliastudios.cameraview.video.FullVideoRecorder.onStart(FullVideoRecorder.java:170)
        at com.otaliastudios.cameraview.video.VideoRecorder.start(VideoRecorder.java:62)
        at com.otaliastudios.cameraview.engine.Camera1Engine.onTakeVideo(Camera1Engine.java:339)
        at com.otaliastudios.cameraview.engine.CameraEngine$23.run(CameraEngine.java:1151)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
2019-09-26 13:20:54.102 26030-26030/cameraapp.cameraapp.com.cameraapp E/CameraEngine: Probably some deadlock in destroy. Current thread: Thread[main,5,main] Handler thread:  Thread[CameraViewEngine,5,]
2019-09-26 13:20:54.107 26030-26030/cameraapp.cameraapp.com.cameraapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cameraapp.cameraapp.com.cameraapp, PID: 26030
    java.lang.RuntimeException: Size not supported for unknown reason. Might be an aspect ratio issue. Desired size:1920x1088
        at com.otaliastudios.cameraview.internal.DeviceEncoders.getSupportedVideoSize(DeviceEncoders.java:214)
        at com.otaliastudios.cameraview.video.FullVideoRecorder.onPrepareMediaRecorder(FullVideoRecorder.java:100)
        at com.otaliastudios.cameraview.video.Full1VideoRecorder.onPrepareMediaRecorder(Full1VideoRecorder.java:44)
        at com.otaliastudios.cameraview.video.FullVideoRecorder.prepareMediaRecorder(FullVideoRecorder.java:45)
        at com.otaliastudios.cameraview.video.FullVideoRecorder.onStart(FullVideoRecorder.java:170)
        at com.otaliastudios.cameraview.video.VideoRecorder.start(VideoRecorder.java:62)
        at com.otaliastudios.cameraview.engine.Camera1Engine.onTakeVideo(Camera1Engine.java:339)
        at com.otaliastudios.cameraview.engine.CameraEngine$23.run(CameraEngine.java:1151)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by natario1** [comment]
Hi @Vitor238 please try with latest version 2.3.0. Feel free to open a new issue if the issue persists.
