### ISSUE TITLE
onConfigureFailed! Session android.hardware.camera2.impl.CameraCaptureSessionImpl@3a3e30a

### ISSUE THREAD

**Issue by bayunvnt** [natario1/CameraView#607]
Hallo, im using this library for my college project, then I have this issue **"onConfigureFailed! Session android.hardware.camera2.impl.CameraCaptureSessionImpl@3a3e30a"**,

this is my stacktrace :
java.lang.RuntimeException · onConfigureFailed! Session android.hardware.camera2.impl.CameraCaptureSessionImpl@2d4c3c1

Camera2Engine:479com.otaliastudios.cameraview.engine.Camera2Engine$4.onConfigureFailed	

CallbackProxies.java:64android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.lambda$onConfigureFailed$1	

Unknown:4android.hardware.camera2.impl.-$$Lambda$CallbackProxies$SessionStateCallbackProxy$gvbTsp9UPpKJAbdycdci_ZW5BeI.run	

Handler.java:873android.os.Handler.handleCallback	

Handler.java:99android.os.Handler.dispatchMessage	

Looper.java:201android.os.Looper.loop	

HandlerThread.java:65android.os.HandlerThread.run

 this error mostly occured on xiaomi device (redmi note 7), can I have any solution? i hope this solve or you can give me any clue, thank you @natario1

**Comment by natario1** [comment]
Can you fill the bug report information? Thanks!

**Comment by coderJohnZhang** [comment]
I have met this issue, too.

11-14 16:46:21.587 19645 19645 E AndroidRuntime: FATAL EXCEPTION: main
11-14 16:46:21.587 19645 19645 E AndroidRuntime: Process: com.tcl.tvcamera, PID: 19645
11-14 16:46:21.587 19645 19645 E AndroidRuntime: java.lang.RuntimeException: onConfigureFailed! Session android.hardware.camera2.impl.CameraCaptureSessionImpl@74bb74e
11-14 16:46:21.587 19645 19645 E AndroidRuntime:        at com.tcl.cameraview.engine.Camera2Engine$4.onConfigureFailed(Camera2Engine.java:531)
11-14 16:46:21.587 19645 19645 E AndroidRuntime:        at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.lambda$onConfigureFailed$1(CallbackProxies.java:64)
11-14 16:46:21.587 19645 19645 E AndroidRuntime:        at android.hardware.camera2.impl.-$$Lambda$CallbackProxies$SessionStateCallbackProxy$gvbTsp9UPpKJAbdycdci_ZW5BeI.run(Unknown Source:4)
11-14 16:46:21.587 19645 19645 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:873)
11-14 16:46:21.587 19645 19645 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
11-14 16:46:21.587 19645 19645 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
11-14 16:46:21.587 19645 19645 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by nsekhar90** [comment]
Im getting this same crash on Nexus 6P.

Is it possible for the library to not throw the exception (resulting in app crash) but report to client that initialization failed & the app can handle it gracefully ?

**Comment by natario1** [comment]
@nsekhar90 do you still get this error if you choose a smaller picture/video/preview stram/frame processing size?

**Comment by nsekhar90** [comment]
Im just using the default options and only for taking a picture (no video). I can try reducing the quality/size.

**Comment by natario1** [comment]
Yeah please do. With camera.setPictureSize(). By default it's the biggest available. You can try camera.setPictureSize(SizeSelectors.smallest()) as an extreme example.

**Comment by nsekhar90** [comment]
That fixes the issue. Is there anything I can do on the client side to adjust this based on device ?

**Comment by natario1** [comment]
Nice to know. What if you **remove that line**, but instead you add `setPreviewStreamSize(SizeSelectors.smallest())` ? Does this fix the issue as well?

You can adjust based on the device with these methods, just pass a SizeSelector that fixes the issue

**Comment by nsekhar90** [comment]
yeah, the `setPreviewStreamSize(SizeSelectors.smallest())` fixes the issue too. So, should I just check for a particular device (Nexus 6p) in this case & add the line `setPreviewStreamSize(SizeSelectors.smallest())` ?

**Comment by natario1** [comment]
I would call something like 
`setPreviewStreamSize(SizeSelectors.and(SizeSelectors.maxWidth(MAX_WIDTH), SizeSelectors.biggest())`.

You should find the value of `MAX_WIDTH` by trying on your nexus (1000? 1200? 1400? 1900?). If you find an exact value please let me know.

**Comment by nsekhar90** [comment]
1000 works best, can we calculate this runtime instead of hard coding it ?

**Comment by nsekhar90** [comment]
Im asking about run time calculation because this crash might occur on other devices right ? I noticed that other people posted about this crash in the top.

**Comment by Frayo44** [comment]
Are there any updates? Also got this on Redmi Note 7 & 8 & Galaxy S8.

**Comment by natario1** [comment]
I'm not actively working on this but my suggestion is to limit the preview stream size with `setPreviewStreamSize()`. If you represent a company feel free to [sponsor](https://github.com/sponsors/natario1) me to let me work on this sooner

**Comment by Frayo44** [comment]
I am not represent a company :/
How can I calculate MAX_WIDTH at runtime?

**Comment by natario1** [comment]
I don't know - you should find something that works for your app, as it likely depends on the picture/video size that you are choosing, whether you are using frame processing or not, what is the frame processing size, ...

**Comment by nxnyk** [comment]
I have the same issue on Redmi 8A

**Comment by tomer8007** [comment]
@natario1 Have an idea of what's the root cause/what flows lead to the `onConfigureFailed` error? Or how to deterministically reproduce this?

**Comment by natario1** [comment]
@tomer8007 it happens when the set of output sizes that we chose (preview stream size, frame processing size if you're using it, picture size when in Mode.PICTURE, video size when in Mode.VIDEO) is rejected by the device. We respect all limits for each size individually, but sometimes the combination of them is too much.

**Comment by nestoleh** [comment]
Does anyone have a working solution for this problem? I got this error on devices Xiaomi (Redmi Note 7, Redmi Note 8, Redmi Note 8T, Redmi 8A) and Samsung (Galaxy A02s, Galaxy A01, Galaxy A10s)

**Comment by 1singhmanmeet** [comment]
It comes mostly on Red devices

**Comment by munir700** [comment]
It comes frequently on Galaxy A02s device

**Comment by sumit007** [comment]
Does anyone able to find a solution for this. I had tried the solution but I am still getting this issue in Redmi 10T 5G devices. 

> I would call something like `setPreviewStreamSize(SizeSelectors.and(SizeSelectors.maxWidth(MAX_WIDTH), SizeSelectors.biggest())`.
> 
> You should find the value of `MAX_WIDTH` by trying on your nexus (1000? 1200? 1400? 1900?). If you find an exact value please let me know.
> 
> Later we might improve this within the lib.
