### ISSUE TITLE
Fatal Exception - Record Front Camera  - SIGSEGV 

### ISSUE THREAD

**Issue by lucazin** [natario1/CameraView#611]
### Describe the bug
Please add a clear description of what the bug is, **and** fill the list below.
- CameraView version: *2.3.0*
- Camera engine used: *both*
- Reproducible in official demo app: *yes*
- Device / Android version: *NEW SAMSUNG A70, API 28*

### To Reproduce
Steps to reproduce the behavior, possibly in the demo app:
1. Open Demo
2. Change to frontal camera
3. Start Recording
4. Back start recording again

repeating 3 and 4 four times maybe will crash..

* i will to set direct frontal camera in xml ..and when i start recording ..bum crash
 Just Happen with frontal camera recording

### Expected behavior
Recording normal , without crash

### XML layout
Demo version

### Screenshots
Just Crash and close 

### Logs

`2019-10-01 09:45:19.603 12023-12348/com.otaliastudios.cameraview.demo A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x22004000e8 in tid 12348 (VideoEncoder), pid 12023 (cameraview.demo)
2019-10-01 09:45:19.686 12366-12366/? E/DEBUG: failed to readlink /proc/12348/fd/83: No such file or directory
2019-10-01 09:45:19.686 12366-12366/? E/DEBUG: failed to readlink /proc/12348/fd/88: No such file or directory
2019-10-01 09:45:19.750 12366-12366/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2019-10-01 09:45:19.750 12366-12366/? A/DEBUG: Build fingerprint: 'samsung/a70qxtc/a70q:9/PPR1.180610.011/A705MNXXU3ASG7:user/release-keys'
2019-10-01 09:45:19.750 12366-12366/? A/DEBUG: Revision: '12'
2019-10-01 09:45:19.750 12366-12366/? A/DEBUG: ABI: 'arm64'
2019-10-01 09:45:19.750 12366-12366/? A/DEBUG: pid: 12023, tid: 12348, name: VideoEncoder  >>> com.otaliastudios.cameraview.demo <<<
2019-10-01 09:45:19.750 12366-12366/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x22004000e8
2019-10-01 09:45:19.750 12366-12366/? A/DEBUG:     x0  0000000000000001  x1  000000000000026b  x2  000000000071f000  x3  000000000000001d
2019-10-01 09:45:19.751 12366-12366/? A/DEBUG:     x4  000000797fae8a38  x5  0000000000000000  x6  00000079694e1000  x7  0000000000000a10
2019-10-01 09:45:19.751 12366-12366/? A/DEBUG:     x8  000000000000026a  x9  000000797fcc8cb0  x10 00000079743930c8  x11 0000000000000000
2019-10-01 09:45:19.751 12366-12366/? A/DEBUG:     x12 0000000000000001  x13 0000000000000010  x14 0000000000000004  x15 00000000004bf0c0
2019-10-01 09:45:19.751 12366-12366/? A/DEBUG:     x16 000000000025f860  x17 0000000000000000  x18 0000000000000a10  x19 000000797400dd00
2019-10-01 09:45:19.751 12366-12366/? A/DEBUG:     x20 0000000000000a10  x21 0000007976099d00  x22 0000007974393350  x23 0000007990891598
2019-10-01 09:45:19.751 12366-12366/? A/DEBUG:     x24 0000002200400000  x25 0000000000000000  x26 0000000000000a10  x27 00000079743935e8
2019-10-01 09:45:19.751 12366-12366/? A/DEBUG:     x28 0000000000000000  x29 00000079743935d0
2019-10-01 09:45:19.751 12366-12366/? A/DEBUG:     sp  00000079743932c0  lr  000000797fac8f34  pc  000000797fac8f44
2019-10-01 09:45:19.911 12366-12366/? A/DEBUG: backtrace:
2019-10-01 09:45:19.911 12366-12366/? A/DEBUG:     #00 pc 0000000000261f44  /vendor/lib64/egl/libGLESv2_adreno.so (EsxResource::UpdateSubResourceDirect(EsxContext*, unsigned int, int, EsxBox const*, EsxSurfaceAccessDesc const*, int)+940)
2019-10-01 09:45:19.911 12366-12366/? A/DEBUG:     #01 pc 0000000000262d48  /vendor/lib64/egl/libGLESv2_adreno.so (EsxTextureObject::PerformShadowCopy(EsxContext*)+608)
2019-10-01 09:45:19.911 12366-12366/? A/DEBUG:     #02 pc 000000000024fa4c  /vendor/lib64/egl/libGLESv2_adreno.so (EsxContext::ValidateProgramTexUnitBoundObjs(EsxProgram*, int)+724)
2019-10-01 09:45:19.911 12366-12366/? A/DEBUG:     #03 pc 000000000024c648  /vendor/lib64/egl/libGLESv2_adreno.so (EsxContext::ValidateGfxState(EsxDrawDescriptor const*)+520)
2019-10-01 09:45:19.912 12366-12366/? A/DEBUG:     #04 pc 00000000002a4350  /vendor/lib64/egl/libGLESv2_adreno.so (EsxContext::DrawArraysInstanced(EsxPrimType, int, unsigned int, unsigned int)+200)
2019-10-01 09:45:19.912 12366-12366/? A/DEBUG:     #05 pc 0000000000441a28  /system/framework/arm64/boot-framework.oat (offset 0x41e000) (android.opengl.GLES10.glDrawArrays [DEDUPED]+168)
2019-10-01 09:45:19.912 12366-12366/? A/DEBUG:     #06 pc 000000000003bf40  /dev/ashmem/dalvik-jit-code-cache_12023_12023 (deleted) (com.otaliastudios.cameraview.filter.BaseFilter.onDraw+80)
2019-10-01 09:45:19.912 12366-12366/? A/DEBUG:     #07 pc 000000000003cca0  /dev/ashmem/dalvik-jit-code-cache_12023_12023 (deleted) (com.otaliastudios.cameraview.filter.BaseFilter.draw+288)
2019-10-01 09:45:19.912 12366-12366/? A/DEBUG:     #08 pc 000000000002bc98  /dev/ashmem/dalvik-jit-code-cache_12023_12023 (deleted) (com.otaliastudios.cameraview.internal.egl.EglViewport.drawFrame+392)
2019-10-01 09:45:19.912 12366-12366/? A/DEBUG:     #09 pc 0000000000559388  /system/lib64/libart.so (art_quick_invoke_stub+584)
2019-10-01 09:45:19.912 12366-12366/? A/DEBUG:     #10 pc 00000000000d02c8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200)
2019-10-01 09:45:19.912 12366-12366/? A/DEBUG:     #11 pc 0000000000280cc0  /system/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+344)
2019-10-01 09:45:19.912 12366-12366/? A/DEBUG:     #12 pc 000000000027acc8  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+968)
2019-10-01 09:45:19.912 12366-12366/? A/DEBUG:     #13 pc 00000000005283dc  /system/lib64/libart.so (MterpInvokeVirtual+588)
2019-10-01 09:45:19.912 12366-12366/? A/DEBUG:     #14 pc 000000000054ba14  /system/lib64/libart.so (ExecuteMterpImpl+14228)
2019-10-01 09:45:19.912 12366-12366/? A/DEBUG:     #15 pc 000000000023726e  /dev/ashmem/dalvik-classes.dex extracted in memory from /data/app/com.otaliastudios.cameraview.demo-O6E2RTxlTGEBT8fWM4tpxw==/base.apk_12023_12023 (deleted) (com.otaliastudios.cameraview.video.encoding.TextureMediaEncoder.onFrame+1110)
2019-10-01 09:45:19.912 12366-12366/? A/DEBUG:     #16 pc 000000000025491c  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.1823628367+488)
2019-10-01 09:45:19.912 12366-12366/? A/DEBUG:     #17 pc 000000000025a410  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
2019-10-01 09:45:19.912 12366-12366/? A/DEBUG:     #18 pc 000000000027acac  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
2019-10-01 09:45:19.912 12366-12366/? A/DEBUG:     #19 pc 000000000052971c  /system/lib64/libart.so (MterpInvokeDirect+296)
2019-10-01 09:45:19.912 12366-12366/? A/DEBUG:     #20 pc 000000000054bb14  /system/lib64/libart.so (ExecuteMterpImpl+14484)
2019-10-01 09:45:19.912 12366-12366/? A/DEBUG:     #21 pc 0000000000236da8  /dev/ashmem/dalvik-classes.dex extracted in memory from /data/app/com.otaliastudios.cameraview.demo-O6E2RTxlTGEBT8fWM4tpxw==/base.apk_12023_12023 (deleted) (com.otaliastudios.cameraview.video.encoding.TextureMediaEncoder.onEvent+148)
2019-10-01 09:45:19.912 12366-12366/? A/DEBUG:     #22 pc 000000000025491c  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.1823628367+488)
2019-10-01 09:45:19.912 12366-12366/? A/DEBUG:     #23 pc 000000000025a410  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
2019-10-01 09:45:19.913 12366-12366/? A/DEBUG:     #24 pc 000000000027acac  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
2019-10-01 09:45:19.913 12366-12366/? A/DEBUG:     #25 pc 00000000005283dc  /system/lib64/libart.so (MterpInvokeVirtual+588)
2019-10-01 09:45:19.913 12366-12366/? A/DEBUG:     #26 pc 000000000054ba14  /system/lib64/libart.so (ExecuteMterpImpl+14228)
2019-10-01 09:45:19.913 12366-12366/? A/DEBUG:     #27 pc 00000000002343da  /dev/ashmem/dalvik-classes.dex extracted in memory from /data/app/com.otaliastudios.cameraview.demo-O6E2RTxlTGEBT8fWM4tpxw==/base.apk_12023_12023 (deleted) (com.otaliastudios.cameraview.video.encoding.MediaEncoder$3.run+106)
2019-10-01 09:45:19.913 12366-12366/? A/DEBUG:     #28 pc 000000000025491c  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.1823628367+488)
2019-10-01 09:45:19.913 12366-12366/? A/DEBUG:     #29 pc 0000000000518c70  /system/lib64/libart.so (artQuickToInterpreterBridge+1020)
2019-10-01 09:45:19.913 12366-12366/? A/DEBUG:     #30 pc 00000000005624fc  /system/lib64/libart.so (art_quick_to_interpreter_bridge+92)
2019-10-01 09:45:19.913 12366-12366/? A/DEBUG:     #31 pc 0000000000029e40  /dev/ashmem/dalvik-jit-code-cache_12023_12023 (deleted) (android.os.Handler.handleCallback+64)
2019-10-01 09:45:19.913 12366-12366/? A/DEBUG:     #32 pc 000000000002aa7c  /dev/ashmem/dalvik-jit-code-cache_12023_12023 (deleted) (android.os.Handler.dispatchMessage+60)
2019-10-01 09:45:19.913 12366-12366/? A/DEBUG:     #33 pc 0000000000015250  /dev/ashmem/dalvik-jit-code-cache_12023_12023 (deleted) (android.os.Looper.loop+1200)
2019-10-01 09:45:19.913 12366-12366/? A/DEBUG:     #34 pc 000000000055964c  /system/lib64/libart.so (art_quick_invoke_static_stub+604)
2019-10-01 09:45:19.913 12366-12366/? A/DEBUG:     #35 pc 00000000000d02e8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+232)
2019-10-01 09:45:19.913 12366-12366/? A/DEBUG:     #36 pc 0000000000280cc0  /system/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+344)
2019-10-01 09:45:19.913 12366-12366/? A/DEBUG:     #37 pc 000000000027acc8  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+968)
2019-10-01 09:45:19.913 12366-12366/? A/DEBUG:     #38 pc 00000000005298e0  /system/lib64/libart.so (MterpInvokeStatic+204)
2019-10-01 09:45:19.913 12366-12366/? A/DEBUG:     #39 pc 000000000054bb94  /system/lib64/libart.so (ExecuteMterpImpl+14612)
2019-10-01 09:45:19.913 12366-12366/? A/DEBUG:     #40 pc 0000000000c77420  /system/framework/boot-framework.vdex (android.os.HandlerThread.run+56)
2019-10-01 09:45:19.913 12366-12366/? A/DEBUG:     #41 pc 000000000025491c  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.1823628367+488)
2019-10-01 09:45:19.913 12366-12366/? A/DEBUG:     #42 pc 0000000000518c70  /system/lib64/libart.so (artQuickToInterpreterBridge+1020)
2019-10-01 09:45:19.913 12366-12366/? A/DEBUG:     #43 pc 00000000005624fc  /system/lib64/libart.so (art_quick_to_interpreter_bridge+92)
2019-10-01 09:45:19.913 12366-12366/? A/DEBUG:     #44 pc 0000000000559388  /system/lib64/libart.so (art_quick_invoke_stub+584)
2019-10-01 09:45:19.913 12366-12366/? A/DEBUG:     #45 pc 00000000000d02c8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200)
2019-10-01 09:45:19.913 12366-12366/? A/DEBUG:     #46 pc 000000000045ed50  /system/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
2019-10-01 09:45:19.913 12366-12366/? A/DEBUG:     #47 pc 000000000045fe0c  /system/lib64/libart.so (art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue*)+424)
2019-10-01 09:45:19.914 12366-12366/? A/DEBUG:     #48 pc 000000000048b22c  /system/lib64/libart.so (art::Thread::CreateCallback(void*)+1120)
2019-10-01 09:45:19.914 12366-12366/? A/DEBUG:     #49 pc 0000000000091c3c  /system/lib64/libc.so (__pthread_start(void*)+36)
2019-10-01 09:45:19.914 12366-12366/? A/DEBUG:     #50 pc 0000000000024200  /system/lib64/libc.so (__start_thread+68)
2019-10-01 09:45:20.302 1033-1033/? E//system/bin/tombstoned: Tombstone written to: /data/tombstones/tombstone_02
2019-10-01 09:45:20.324 614-614/? E/audit: type=1701 audit(1569933920.315:6751): auid=4294967295 uid=10225 gid=10225 ses=4294967295 subj=u:r:untrusted_app:s0:c225,c256,c512,c768 pid=12023 comm="VideoEncoder" exe="/system/bin/app_process64" sig=11 res=1
2019-10-01 09:45:20.358 914-1744/? E/NativeSemDvfsCpuManager: release:: Start
2019-10-01 09:45:20.358 914-1744/? E/SemOpenPerfStorageManager: release:: Start
2019-10-01 09:45:20.358 914-1744/? E/SemOpenPerfStorageManager: release:: DVFS lock is already released. Previous lock will be acquire first.
2019-10-01 09:45:20.387 12380-12380/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2019-10-01 09:45:20.388 12380-12380/? E/Zygote: accessInfo : 1
2019-10-01 09:45:20.405 939-8067/? E/OMXNodeInstance: !!! Observer died. Quickly, do something, ... anything...
2019-10-01 09:45:20.405 939-18367/? E/OMXNodeInstance: !!! Observer died. Quickly, do something, ... anything...
2019-10-01 09:45:20.405 1328-1782/? E/InputDispatcher: channel '534f336 Toast (server)' ~ Channel is unrecoverably broken and will be disposed!
2019-10-01 09:45:20.423 12380-12380/? E/android.dqagen: Not starting debugger since process cannot load the jdwp agent.
2019-10-01 09:45:20.429 2168-3764/? E/rs$DefaultThreadFactory: ===== Detect pool-thread leak =====
2019-10-01 09:45:20.429 2168-3764/? E/rs$DefaultThreadFactory: dalvik.system.VMStack.getThreadStackTrace(Native Method)
2019-10-01 09:45:20.429 2168-3764/? E/rs$DefaultThreadFactory: java.lang.Thread.getStackTrace(Thread.java:1538)
2019-10-01 09:45:20.429 2168-3764/? E/rs$DefaultThreadFactory: java.util.concurrent.Executors$DefaultThreadFactory.newThread(Executors.java:569)
2019-10-01 09:45:20.429 2168-3764/? E/rs$DefaultThreadFactory: spg.newThread(Unknown Source:9)
2019-10-01 09:45:20.429 2168-3764/? E/rs$DefaultThreadFactory: java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:636)
2019-10-01 09:45:20.430 2168-3764/? E/rs$DefaultThreadFactory: java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950)
2019-10-01 09:45:20.430 2168-3764/? E/rs$DefaultThreadFactory: java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1393)
2019-10-01 09:45:20.430 2168-3764/? E/rs$DefaultThreadFactory: sjn.a(:com.google.android.gms@19275037@19.2.75 (100400-269183835):14)
2019-10-01 09:45:20.430 2168-3764/? E/rs$DefaultThreadFactory: sjn.execute(:com.google.android.gms@19275037@19.2.75 (100400-269183835):2)
2019-10-01 09:45:20.430 2168-3764/? E/rs$DefaultThreadFactory: bpua.execute(:com.google.android.gms@19275037@19.2.75 (100400-269183835):7)
2019-10-01 09:45:20.430 2168-3764/? E/rs$DefaultThreadFactory: bptp.execute(:com.google.android.gms@19275037@19.2.75 (100400-269183835):1)
2019-10-01 09:45:20.430 2168-3764/? E/rs$DefaultThreadFactory: bpqp.b(:com.google.android.gms@19275037@19.2.75 (100400-269183835):3)
2019-10-01 09:45:20.430 2168-3764/? E/rs$DefaultThreadFactory: bpqp.a(:com.google.android.gms@19275037@19.2.75 (100400-269183835):51)
2019-10-01 09:45:20.430 2168-3764/? E/rs$DefaultThreadFactory: bprg.a(:com.google.android.gms@19275037@19.2.75 (100400-269183835):1)
2019-10-01 09:45:20.430 2168-3764/? E/rs$DefaultThreadFactory: bedo.c(:com.google.android.gms@19275037@19.2.75 (100400-269183835):2)
2019-10-01 09:45:20.430 2168-3764/? E/rs$DefaultThreadFactory: bedo.b(Unknown Source:0)
2019-10-01 09:45:20.430 2168-3764/? E/rs$DefaultThreadFactory: beca.a(:com.google.android.gms@19275037@19.2.75 (100400-269183835):8)
2019-10-01 09:45:20.430 2168-3764/? E/rs$DefaultThreadFactory: avpv.a(:com.google.android.gms@19275037@19.2.75 (100400-269183835):1)
2019-10-01 09:45:20.430 2168-3764/? E/rs$DefaultThreadFactory: avps.a(:com.google.android.gms@19275037@19.2.75 (100400-269183835):9)
2019-10-01 09:45:20.430 2168-3764/? E/rs$DefaultThreadFactory: avmp.a(:com.google.android.gms@19275037@19.2.75 (100400-269183835):15)
2019-10-01 09:45:20.430 2168-3764/? E/rs$DefaultThreadFactory: avmp.a(:com.google.android.gms@19275037@19.2.75 (100400-269183835):60)
2019-10-01 09:45:20.430 2168-3764/? E/rs$DefaultThreadFactory: zvv.run(:com.google.android.gms@19275037@19.2.75 (100400-269183835):17)
2019-10-01 09:45:20.430 2168-3764/? E/rs$DefaultThreadFactory: bkgy.run(:com.google.android.gms@19275037@19.2.75 (100400-269183835):2)
2019-10-01 09:45:20.430 2168-3764/? E/rs$DefaultThreadFactory: sjm.b(:com.google.android.gms@19275037@19.2.75 (100400-269183835):33)
2019-10-01 09:45:20.430 2168-3764/? E/rs$DefaultThreadFactory: sjm.run(:com.google.android.gms@19275037@19.2.75 (100400-269183835):21)
2019-10-01 09:45:20.430 2168-3764/? E/rs$DefaultThreadFactory: java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2019-10-01 09:45:20.430 2168-3764/? E/rs$DefaultThreadFactory: java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2019-10-01 09:45:20.430 2168-3764/? E/rs$DefaultThreadFactory: spf.run(Unknown Source:7)
2019-10-01 09:45:20.430 2168-3764/? E/rs$DefaultThreadFactory: java.lang.Thread.run(Thread.java:764)
2019-10-01 09:45:20.464 1328-1554/? E/WindowManager: RemoteException occurs on reporting focusChanged, w=Window{6a2d416 u0 com.otaliastudios.cameraview.demo/com.otaliastudios.cameraview.demo.CameraActivity}`

### APK
i dont have my apk yet...but in my project happens again with 2.2.0

**Comment by lucazin** [comment]
I tested with other videocodec  like h263 and h264 and default...  i get the same


Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x6300750064006f in tid 22635 (VideoEncoder), pid 20068

2019-10-01 10:41:44.168 22656-22656/? A/DEBUG: Build fingerprint: 'samsung/a70qxtc/a70q:9/PPR1.180610.011/A705MNXXU3ASG7:user/release-keys'
2019-10-01 10:41:44.168 22656-22656/? A/DEBUG: Revision: '12'
2019-10-01 10:41:44.168 22656-22656/? A/DEBUG: ABI: 'arm64'
2019-10-01 10:41:44.168 22656-22656/? A/DEBUG: pid: 20068, tid: 22635, name: VideoEncoder  >>> br.com.oneplace <<<

2019-10-01 10:41:44.303 22656-22656/? A/DEBUG: backtrace:
2019-10-01 10:41:44.303 22656-22656/? A/DEBUG:     #00 pc 000000000026a498  /vendor/lib64/egl/libGLESv2_adreno.so (EsxBltLib::CopyHostPtrBltSw(EsxBltCopyHostPtr const*)+416)
2019-10-01 10:41:44.303 22656-22656/? A/DEBUG:     #01 pc 0000000000261ff0  /vendor/lib64/egl/libGLESv2_adreno.so (EsxResource::UpdateSubResourceDirect(EsxContext*, unsigned int, int, EsxBox const*, EsxSurfaceAccessDesc const*, int)+1112)
2019-10-01 10:41:44.303 22656-22656/? A/DEBUG:     #02 pc 0000000000262d48  /vendor/lib64/egl/libGLESv2_adreno.so (EsxTextureObject::PerformShadowCopy(EsxContext*)+608)
2019-10-01 10:41:44.303 22656-22656/? A/DEBUG:     #03 pc 000000000024fa4c  /vendor/lib64/egl/libGLESv2_adreno.so (EsxContext::ValidateProgramTexUnitBoundObjs(EsxProgram*, int)+724)
2019-10-01 10:41:44.303 22656-22656/? A/DEBUG:     #04 pc 000000000024c648  /vendor/lib64/egl/libGLESv2_adreno.so (EsxContext::ValidateGfxState(EsxDrawDescriptor const*)+520)
2019-10-01 10:41:44.303 22656-22656/? A/DEBUG:     #05 pc 00000000002a4350  /vendor/lib64/egl/libGLESv2_adreno.so (EsxContext::DrawArraysInstanced(EsxPrimType, int, unsigned int, unsigned int)+200)
2019-10-01 10:41:44.303 22656-22656/? A/DEBUG:     #06 pc 0000000000441a28  /system/framework/arm64/boot-framework.oat (offset 0x41e000) (android.opengl.GLES10.glDrawArrays [DEDUPED]+168)
2019-10-01 10:41:44.303 22656-22656/? A/DEBUG:     #07 pc 00000000000b91c8  /dev/ashmem/dalvik-jit-code-cache_20068_20068 (deleted) (com.otaliastudios.cameraview.filter.BaseFilter.onDraw+56)
2019-10-01 10:41:44.303 22656-22656/? A/DEBUG:     #08 pc 00000000000ba31c  /dev/ashmem/dalvik-jit-code-cache_20068_20068 (deleted) (com.otaliastudios.cameraview.filter.BaseFilter.draw+220)
2019-10-01 10:41:44.303 22656-22656/? A/DEBUG:     #09 pc 00000000000a4368  /dev/ashmem/dalvik-jit-code-cache_20068_20068 (deleted) (com.otaliastudios.cameraview.internal.egl.EglViewport.drawFrame+296)
2019-10-01 10:41:44.303 22656-22656/? A/DEBUG:     #10 pc 00000000000bfe70  /dev/ashmem/dalvik-jit-code-cache_20068_20068 (deleted) (com.otaliastudios.cameraview.video.encoding.TextureMediaEncoder.onFrame+2288)
2019-10-01 10:41:44.303 22656-22656/? A/DEBUG:     #11 pc 00000000000ef078  /dev/ashmem/dalvik-jit-code-cache_20068_20068 (deleted) (com.otaliastudios.cameraview.video.encoding.TextureMediaEncoder.onEvent+296)
2019-10-01 10:41:44.303 22656-22656/? A/DEBUG:     #12 pc 00000000000c2054  /dev/ashmem/dalvik-jit-code-cache_20068_20068 (deleted) (com.otaliastudios.cameraview.video.encoding.MediaEncoder$3.run+324)
2019-10-01 10:41:44.303 22656-22656/? A/DEBUG:     #13 pc 00000000000a19d0  /dev/ashmem/dalvik-jit-code-cache_20068_20068 (deleted) (android.os.Handler.handleCallback+64)
2019-10-01 10:41:44.303 22656-22656/? A/DEBUG:     #14 pc 00000000000a20ac  /dev/ashmem/dalvik-jit-code-cache_20068_20068 (deleted) (android.os.Handler.dispatchMessage+60)
2019-10-01 10:41:44.303 22656-22656/? A/DEBUG:     #15 pc 0000000000087f70  /dev/ashmem/dalvik-jit-code-cache_20068_20068 (deleted) (android.os.Looper.loop+1200)
2019-10-01 10:41:44.303 22656-22656/? A/DEBUG:     #16 pc 000000000055964c  /system/lib64/libart.so (art_quick_invoke_static_stub+604)
2019-10-01 10:41:44.303 22656-22656/? A/DEBUG:     #17 pc 00000000000d02e8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+232)
2019-10-01 10:41:44.303 22656-22656/? A/DEBUG:     #18 pc 0000000000280cc0  /system/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+344)
2019-10-01 10:41:44.303 22656-22656/? A/DEBUG:     #19 pc 000000000027acc8  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+968)
2019-10-01 10:41:44.304 22656-22656/? A/DEBUG:     #20 pc 00000000005298e0  /system/lib64/libart.so (MterpInvokeStatic+204)
2019-10-01 10:41:44.304 22656-22656/? A/DEBUG:     #21 pc 000000000054bb94  /system/lib64/libart.so (ExecuteMterpImpl+14612)
2019-10-01 10:41:44.304 22656-22656/? A/DEBUG:     #22 pc 0000000000c77420  /system/framework/boot-framework.vdex (android.os.HandlerThread.run+56)
2019-10-01 10:41:44.304 22656-22656/? A/DEBUG:     #23 pc 000000000025491c  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.1823628367+488)
2019-10-01 10:41:44.304 22656-22656/? A/DEBUG:     #24 pc 0000000000518c70  /system/lib64/libart.so (artQuickToInterpreterBridge+1020)
2019-10-01 10:41:44.304 22656-22656/? A/DEBUG:     #25 pc 00000000005624fc  /system/lib64/libart.so (art_quick_to_interpreter_bridge+92)
2019-10-01 10:41:44.304 22656-22656/? A/DEBUG:     #26 pc 0000000000559388  /system/lib64/libart.so (art_quick_invoke_stub+584)

2019-10-01 10:41:45.258 863-1948/? E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -32
2019-10-01 10:41:45.258 863-1948/? E/Camera3-OutputStream: returnBufferCheckedLocked: Stream 0: Error queueing buffer to native window: Broken pipe (-32)
2019-10-01 10:41:45.258 863-1948/? E/Camera3-Device: Can't return buffer to its stream: Broken pipe (-32)


2019-10-01 10:41:45.262 1328-1554/? E/WindowManager: RemoteException occurs on reporting focusChanged, w=Window{a0ccedb u0 br.com.oneplace/aplicativo.oneplace.Fragments.AppEstabelecimento.Default_Features.VideoComercial.VideoComercial EXITING}
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:1143)
        at android.view.IWindow$Stub$Proxy.windowFocusChanged(IWindow.java:500)
        at com.android.server.wm.WindowState.reportFocusChangedSerialized(WindowState.java:3959)
        at com.android.server.wm.WindowManagerService$H.handleMessage(WindowManagerService.java:5493)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:65)
        at com.android.server.ServiceThread.run(ServiceThread.java:44)


2019-10-01 10:41:44.304 22656-22656/? A/DEBUG:     #27 pc 00000000000d02c8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200)
2019-10-01 10:41:44.304 22656-22656/? A/DEBUG:     #28 pc 000000000045ed50  /system/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
2019-10-01 10:41:44.304 22656-22656/? A/DEBUG:     #29 pc 000000000045fe0c  /system/lib64/libart.so (art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue*)+424)
2019-10-01 10:41:44.304 22656-22656/? A/DEBUG:     #30 pc 000000000048b22c  /system/lib64/libart.so (art::Thread::CreateCallback(void*)+1120)
2019-10-01 10:41:44.304 22656-22656/? A/DEBUG:     #31 pc 0000000000091c3c  /system/lib64/libc.so (__pthread_start(void*)+36)
2019-10-01 10:41:44.304 22656-22656/? A/DEBUG:     #32 pc 0000000000024200  /system/lib64/libc.so (__start_thread+68)

**Comment by lucazin** [comment]
Other point i have tested now.

If i record with takevideo too and after videopreview back and record again.. watch video preview ..back and record again .. they give a expection sigsegv

**Comment by lucazin** [comment]
same  #606
