### ISSUE TITLE
Crashed with 'ConcurrentModificationException' after taking Picture

### ISSUE THREAD

**Issue by usmanrana07** [natario1/CameraView#637]
### Describe the bug
Please add a clear description of what the bug is, **and** fill the list below.
- CameraView version: *2.3.0*
- Camera engine used: *camera1/camera2/both*
- Device / Android version: *Note5, API 22*

I recorded video sometimes and then tried to takePicture but it crashed with following logs:

```
Process: com.fayvo, PID: 32037
    java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextEntry(HashMap.java:787)
        at java.util.HashMap$KeyIterator.next(HashMap.java:814)
        at com.otaliastudios.cameraview.preview.GlCameraPreview$Renderer.onDrawFrame(GlCameraPreview.java:230)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1561)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1278)
```

**Comment by natario1** [comment]
This was fixed in latest version.
