### ISSUE TITLE
I used MultiFilter ，when app onResume，it crash

### ISSUE THREAD

**Issue by caiyoufei** [natario1/CameraView#648]
java.lang.RuntimeException: Error during glUniformMatrix4fv glError 0x 501
        at com.otaliastudios.cameraview.internal.GlUtils.checkError(GlUtils.java:25)
        at com.otaliastudios.cameraview.filter.BaseFilter.onPreDraw(BaseFilter.java:192)
        at com.otaliastudios.cameraview.filter.BaseFilter.draw(BaseFilter.java:182)
        at com.otaliastudios.cameraview.filter.MultiFilter.draw(MultiFilter.java:260)
        at com.otaliastudios.cameraview.internal.egl.EglViewport.drawFrame(EglViewport.java:93)
        at com.otaliastudios.cameraview.preview.GlCameraPreview$Renderer.onDrawFrame(GlCameraPreview.java:215)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1590)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1286)

**Comment by caiyoufei** [comment]
![image](https://user-images.githubusercontent.com/11989916/66822674-eb9eba80-ef6e-11e9-9f02-0117c2b770ba.png)
change demo code

**Comment by natario1** [comment]
Thanks for reporting!

**Comment by harikumar007** [comment]
Fatal Exception: java.lang.RuntimeException
Error during glCreateShader type=35633 glError 0x 501
com.otaliastudios.cameraview.internal.GlUtils.checkError (GlUtils.java:31)

Getting this error when using takeSnapShot option...
