### ISSUE TITLE
Crash When first time RECORD_AUDIO Permission is denied and then accepted

### ISSUE THREAD

**Issue by usmanrana07** [natario1/CameraView#664]
### Describe the bug
Please add a clear description of what the bug is, **and** fill the list below.
- CameraView version: *2.4.0*
- Camera engine used: *both*
- Device / Android version: *Huawei Y9 , 9.1*

If you deny the RECORD_AUDIO permission first time and then accept the permission request. Then when you press he device power key and again unlock the phone , the app crashes with following logs:

```
Fatal Exception: java.lang.RuntimeException: Unknown CameraPreview output class.
       at com.otaliastudios.cameraview.engine.Camera1Engine.onStartBind + 181(Camera1Engine.java:181)
       at com.otaliastudios.cameraview.engine.CameraEngine$7.call + 444(CameraEngine.java:444)
       at com.otaliastudios.cameraview.engine.CameraEngine$7.call + 441(CameraEngine.java:441)
       at com.otaliastudios.cameraview.engine.Step$2.then + 117(Step.java:117)
       at com.otaliastudios.cameraview.engine.Step$2.then + 112(Step.java:112)
       at com.google.android.gms.tasks.zzf.run + 2(:2)
       at com.otaliastudios.cameraview.internal.utils.WorkerHandler.run + 129(WorkerHandler.java:129)
       at com.otaliastudios.cameraview.internal.utils.WorkerHandler$1.execute + 104(WorkerHandler.java:104)
       at com.google.android.gms.tasks.zze.onComplete + 6(:6)
       at com.google.android.gms.tasks.zzr.zza + 19(:19)
       at com.google.android.gms.tasks.zzu.zze + 132(:132)
       at com.google.android.gms.tasks.zzu.continueWithTask + 74(:74)
       at com.otaliastudios.cameraview.engine.Step.doStart + 112(Step.java:112)
       at com.otaliastudios.cameraview.engine.Step.doStart + 105(Step.java:105)
       at com.otaliastudios.cameraview.engine.CameraEngine.startBind + 441(CameraEngine.java:441)
       at com.otaliastudios.cameraview.engine.CameraEngine.access$500 + 123(CameraEngine.java:123)
       at com.otaliastudios.cameraview.engine.CameraEngine$17$1$2.then + 735(CameraEngine.java:735)
       at com.otaliastudios.cameraview.engine.CameraEngine$17$1$2.then + 730(CameraEngine.java:730)
       at com.google.android.gms.tasks.zzp.run + 2(:2)
       at com.otaliastudios.cameraview.internal.utils.WorkerHandler.run + 129(WorkerHandler.java:129)
       at com.otaliastudios.cameraview.internal.utils.WorkerHandler$1.execute + 104(WorkerHandler.java:104)
       at com.google.android.gms.tasks.zzo.onComplete + 6(:6)
       at com.google.android.gms.tasks.zzr.zza + 19(:19)
       at com.google.android.gms.tasks.zzu.zze + 132(:132)
       at com.google.android.gms.tasks.zzu.onSuccessTask + 78(:78)
       at com.otaliastudios.cameraview.engine.CameraEngine$17$1.call + 730(CameraEngine.java:730)
       at com.otaliastudios.cameraview.engine.CameraEngine$17$1.call + 721(CameraEngine.java:721)
       at com.otaliastudios.cameraview.engine.Step$2.then + 117(Step.java:117)
       at com.otaliastudios.cameraview.engine.Step$2.then + 112(Step.java:112)
       at com.google.android.gms.tasks.zzf.run + 2(:2)
       at com.otaliastudios.cameraview.internal.utils.WorkerHandler.run + 129(WorkerHandler.java:129)
       at com.otaliastudios.cameraview.internal.utils.WorkerHandler$1.execute + 104(WorkerHandler.java:104)
       at com.google.android.gms.tasks.zze.onComplete + 6(:6)
       at com.google.android.gms.tasks.zzr.zza + 19(:19)
       at com.google.android.gms.tasks.zzu.zze + 132(:132)
       at com.google.android.gms.tasks.zzu.continueWithTask + 74(:74)
       at com.otaliastudios.cameraview.engine.Step.doStart + 112(Step.java:112)
       at com.otaliastudios.cameraview.engine.Step.doStart + 105(Step.java:105)
       at com.otaliastudios.cameraview.engine.CameraEngine$17.run + 721(CameraEngine.java:721)
       at android.os.Handler.handleCallback + 907(Handler.java:907)
       at android.os.Handler.dispatchMessage + 105(Handler.java:105)
       at android.os.Looper.loop + 216(Looper.java:216)
       at android.os.HandlerThread.run + 65(HandlerThread.java:65)
```

**Comment by simkis** [comment]
Got same crash on Galaxy A5 (2017) android 8.0.0

`Fatal Exception: java.lang.RuntimeException: Unknown CameraPreview output class.
       at com.otaliastudios.cameraview.engine.Camera1Engine.onStartBind(Camera1Engine.java:181)
       at com.otaliastudios.cameraview.engine.CameraEngine$7.call(CameraEngine.java:444)
       at com.otaliastudios.cameraview.engine.CameraEngine$7.call(CameraEngine.java:441)
       at com.otaliastudios.cameraview.engine.Step$2.then(Step.java:117)
       at com.otaliastudios.cameraview.engine.Step$2.then(Step.java:112)
       at com.google.android.gms.tasks.zzf.run(zzf.java:2)
       at com.otaliastudios.cameraview.internal.utils.WorkerHandler.run(WorkerHandler.java:129)
       at com.otaliastudios.cameraview.internal.utils.WorkerHandler$1.execute(WorkerHandler.java:104)
       at com.google.android.gms.tasks.zze.onComplete(zze.java:6)
       at com.google.android.gms.tasks.zzr.zza(zzr.java:19)
       at com.google.android.gms.tasks.zzu.zze(zzu.java:132)
       at com.google.android.gms.tasks.zzu.continueWithTask(zzu.java:74)
       at com.otaliastudios.cameraview.engine.Step.doStart(Step.java:112)
       at com.otaliastudios.cameraview.engine.Step.doStart(Step.java:105)
       at com.otaliastudios.cameraview.engine.CameraEngine.startBind(CameraEngine.java:441)
       at com.otaliastudios.cameraview.engine.CameraEngine.access$500(CameraEngine.java:123)
       at com.otaliastudios.cameraview.engine.CameraEngine$17$1$2.then(CameraEngine.java:735)
       at com.otaliastudios.cameraview.engine.CameraEngine$17$1$2.then(CameraEngine.java:730)
       at com.google.android.gms.tasks.zzp.run(zzp.java:2)
       at com.otaliastudios.cameraview.internal.utils.WorkerHandler.run(WorkerHandler.java:129)
       at com.otaliastudios.cameraview.internal.utils.WorkerHandler$1.execute(WorkerHandler.java:104)
       at com.google.android.gms.tasks.zzo.onComplete(zzo.java:6)
       at com.google.android.gms.tasks.zzr.zza(zzr.java:19)
       at com.google.android.gms.tasks.zzu.zze(zzu.java:132)
       at com.google.android.gms.tasks.zzu.onSuccessTask(zzu.java:78)
       at com.otaliastudios.cameraview.engine.CameraEngine$17$1.call(CameraEngine.java:730)
       at com.otaliastudios.cameraview.engine.CameraEngine$17$1.call(CameraEngine.java:721)
       at com.otaliastudios.cameraview.engine.Step$2.then(Step.java:117)
       at com.otaliastudios.cameraview.engine.Step$2.then(Step.java:112)
       at com.google.android.gms.tasks.zzf.run(zzf.java:2)
       at com.otaliastudios.cameraview.internal.utils.WorkerHandler.run(WorkerHandler.java:129)
       at com.otaliastudios.cameraview.internal.utils.WorkerHandler$1.execute(WorkerHandler.java:104)
       at com.google.android.gms.tasks.zze.onComplete(zze.java:6)
       at com.google.android.gms.tasks.zzr.zza(zzr.java:19)
       at com.google.android.gms.tasks.zzu.zze(zzu.java:132)
       at com.google.android.gms.tasks.zzu.continueWithTask(zzu.java:74)
       at com.otaliastudios.cameraview.engine.Step.doStart(Step.java:112)
       at com.otaliastudios.cameraview.engine.Step.doStart(Step.java:105)
       at com.otaliastudios.cameraview.engine.CameraEngine$17.run(CameraEngine.java:721)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.os.HandlerThread.run(HandlerThread.java:65)`
