### ISSUE TITLE
Error onEncodingEnd java.lang.IllegalStateException: Failed to stop the muxer

### ISSUE THREAD

**Issue by Ahmed-Adel-Ismail** [natario1/CameraView#753]
This error still persists :
library version : com.otaliastudios:cameraview:2.6.1'
what happened : I stopped the video
stack trace :

2020-01-16 06:40:16.146 E/MediaMuxer: stop() is called in invalid state 3
2020-01-16 06:40:16.147 E/SnapshotVideoRecorder: Error onEncodingEnd java.lang.IllegalStateException: Failed to stop the muxer
java.lang.IllegalStateException: Failed to stop the muxer
at android.media.MediaMuxer.nativeStop(Native Method)
at android.media.MediaMuxer.stop(MediaMuxer.java:454)
at com.otaliastudios.cameraview.video.encoding.MediaEncoderEngine.end(MediaEncoderEngine.java:224)
at com.otaliastudios.cameraview.video.encoding.MediaEncoderEngine.access$1100(MediaEncoderEngine.java:57)
at com.otaliastudios.cameraview.video.encoding.MediaEncoderEngine$Controller$3.run(MediaEncoderEngine.java:412)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:207)
at android.os.HandlerThread.run(HandlerThread.java:65)
2020-01-16 06:40:16.149 E/CameraEngine: onVideoResult result is null: something went wrong. java.lang.IllegalStateException: Failed to stop the muxer
java.lang.IllegalStateException: Failed to stop the muxer
at android.media.MediaMuxer.nativeStop(Native Method)
at android.media.MediaMuxer.stop(MediaMuxer.java:454)
at com.otaliastudios.cameraview.video.encoding.MediaEncoderEngine.end(MediaEncoderEngine.java:224)
at com.otaliastudios.cameraview.video.encoding.MediaEncoderEngine.access$1100(MediaEncoderEngine.java:57)
at com.otaliastudios.cameraview.video.encoding.MediaEncoderEngine$Controller$3.run(MediaEncoderEngine.java:412)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:207)
at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by esemchenko** [comment]
This error still occurs on some ZTE devices

**Comment by luojianping168** [comment]
me too
