### ISSUE TITLE
Android 6.0 crash, Fatal Exception: java.lang.IllegalStateException

### ISSUE THREAD

**Issue by adaonder** [natario1/CameraView#757]
### Describe the bug
- CameraView version: 2.4.0
- Android version: 6.0

### Logs

Fatal Exception: java.lang.IllegalStateException: Fragment TaskSelectFragment{7b3b326 (1a710908-6986-4af4-b339-54fadbcbf892)} not attached to a context.
       at androidx.fragment.app.Fragment.requireContext(Fragment.java:774)
       at androidx.fragment.app.Fragment.getResources(Fragment.java:838)
       at androidx.fragment.app.Fragment.getString(Fragment.java:860)
       at com.xxx.fragment.main.TaskSelectFragment.setVisibleList(TaskSelectFragment.java:198)
       at com.xxx.fragment.main.TaskSelectFragment.lambda$getTaskUpdate$5$TaskSelectFragment(TaskSelectFragment.java:188)
       at com.xxx.fragment.main.-$$Lambda$TaskSelectFragment$YXeDMfhk7eFjJbx7Kf-j2_CQ3io.run(lambda)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5728)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

**Comment by natario1** [comment]
This doesn't seem related to this library.
