### ISSUE TITLE
camera crashes at startup

### ISSUE THREAD

**Issue by mariuspena** [natario1/CameraView#801]
### How do I?
I have lots of crashes in crashlytics with the stacktrace below. Could someone help me with a tip or where should I start investigating ?
 
`Fatal Exception: java.lang.RuntimeException: getParameters failed (empty parameters)
       at android.hardware.Camera.native_getParameters(Camera.java)
       at android.hardware.Camera.getParameters(Camera.java:1953)
       at com.otaliastudios.cameraview.engine.Camera1Engine.getPreviewStreamAvailableSizes(Camera1Engine.java:102)
       at com.otaliastudios.cameraview.engine.CameraBaseEngine.computePreviewStreamSize(CameraBaseEngine.java:846)
       at com.otaliastudios.cameraview.engine.Camera1Engine.onStartBind(Camera1Engine.java:195)
       at com.otaliastudios.cameraview.engine.CameraEngine$8.call(CameraEngine.java:470)
       at com.otaliastudios.cameraview.engine.CameraEngine$8.call(CameraEngine.java:466)
       at com.otaliastudios.cameraview.engine.orchestrator.CameraStateOrchestrator$2.call(CameraStateOrchestrator.java:69)
       at com.otaliastudios.cameraview.engine.orchestrator.CameraStateOrchestrator$2.call(CameraStateOrchestrator.java:60)
       at com.otaliastudios.cameraview.engine.orchestrator.CameraOrchestrator$2.onComplete(CameraOrchestrator.java:100)
       at com.google.android.gms.tasks.zzj.run(zzj.java:4)
       at com.otaliastudios.cameraview.internal.utils.WorkerHandler.run(WorkerHandler.java:137)
       at com.otaliastudios.cameraview.internal.utils.WorkerHandler$2.execute(WorkerHandler.java:112)
       at com.google.android.gms.tasks.zzi.onComplete(zzi.java:10)
       at com.google.android.gms.tasks.zzr.zza(zzr.java:19)
       at com.google.android.gms.tasks.zzu.trySetResult(zzu.java:94)
       at com.google.android.gms.tasks.TaskCompletionSource.trySetResult(TaskCompletionSource.java:10)
       at com.otaliastudios.cameraview.engine.orchestrator.CameraOrchestrator$2$1.onComplete(CameraOrchestrator.java:116)
       at com.otaliastudios.cameraview.engine.orchestrator.CameraOrchestrator$4.run(CameraOrchestrator.java:195)
       at com.otaliastudios.cameraview.internal.utils.WorkerHandler.run(WorkerHandler.java:137)
       at com.otaliastudios.cameraview.engine.orchestrator.CameraOrchestrator.applyCompletionListener(CameraOrchestrator.java:192)
       at com.otaliastudios.cameraview.engine.orchestrator.CameraOrchestrator.access$100(CameraOrchestrator.java:32)
       at com.otaliastudios.cameraview.engine.orchestrator.CameraOrchestrator$2.onComplete(CameraOrchestrator.java:101)
       at com.otaliastudios.cameraview.engine.orchestrator.CameraOrchestrator$4.run(CameraOrchestrator.java:195)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.os.HandlerThread.run(HandlerThread.java:61)`

### Version used
2.6.1

**Comment by duanniston** [comment]
I have the same issue @mariuspena
