### ISSUE TITLE
NoSuchMethodError in Egloo last version

### ISSUE THREAD

**Issue by TemMax** [natario1/CameraView#803]
After capturing some video it passed to transcoder.
And on start of transcoding throws NoSuchMethodError. I suppose it depends on last Egloo version, but I don't know which one crashed: CameraView or Transcoder (which one use Egloo).
Log: 
```
E/Transcoder: Unexpected error while transcoding
    java.lang.NoSuchMethodError: No virtual method getTextureId()I in class Lcom/otaliastudios/opengl/program/GlTextureProgram; or its super classes (declaration of 'com.otaliastudios.opengl.program.GlTextureProgram' appears in /data/app/com.example.app-249iyqfox4LQ9odmXSXyDg==/base.apk!classes3.dex)
        at com.otaliastudios.transcoder.transcode.internal.VideoDecoderOutput.<init>(VideoDecoderOutput.java:60)
        at com.otaliastudios.transcoder.transcode.VideoTrackTranscoder.onConfigureDecoder(VideoTrackTranscoder.java:103)
        at com.otaliastudios.transcoder.transcode.BaseTrackTranscoder.setUp(BaseTrackTranscoder.java:75)
        at com.otaliastudios.transcoder.engine.Engine.openCurrentStep(Engine.java:190)
        at com.otaliastudios.transcoder.engine.Engine.getCurrentTrackTranscoder(Engine.java:219)
        at com.otaliastudios.transcoder.engine.Engine.transcode(Engine.java:367)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:134)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:124)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

CameraView: 2.6.2
Engine: camera2
Device: Pixel 2, API 28

How to reproduce: capture some video and after pass it to Transcoder

**Comment by natario1** [comment]
Just use latest version of both
