### ISSUE TITLE
Continue video snapshot recording while changing CameraView width and height

### ISSUE THREAD

**Issue by chitrang200889** [natario1/CameraView#855]
I am using GLSurfaceView for taking a video snapshot. Video is being played with PlayerView(ExoPlayer) inside a square layout, and on the right top corner I need to show CameraView, and vice versa. UI is kind of similar as in WhatsApp video call, where a user can switch between two views.

Is there a way to continue video snapshot recording and switch the position between CameraView and PalyerView? So basically it requires to change width and height of CameraView width and height while recording video.

As of now, it throws an exception, 

`
E/SnapshotVideoRecorder: Error onEncodingEnd java.lang.IllegalStateException: Failed to stop the muxer
    java.lang.IllegalStateException: Failed to stop the muxer
        at android.media.MediaMuxer.nativeStop(Native Method)
        at android.media.MediaMuxer.stop(MediaMuxer.java:466)
        at com.otaliastudios.cameraview.video.encoding.MediaEncoderEngine.end(MediaEncoderEngine.java:223)
        at com.otaliastudios.cameraview.video.encoding.MediaEncoderEngine.access$1100(MediaEncoderEngine.java:56)
        at com.otaliastudios.cameraview.video.encoding.MediaEncoderEngine$Controller$3.run(MediaEncoderEngine.java:411)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.os.HandlerThread.run(HandlerThread.java:67)
`

**Comment by chitrang200889** [comment]
I found the below solution for this and it seems working fine to me. However, I need your opinion and confirmation for the same. 

So for the solution, I went through different classes in the code to understand it and I concluded this to modify **CameraBaseEngine** class and its method **onSurfaceChanged()** by adding **isTakingVideo()** in if condition.

```
    @Override
    public final void onSurfaceChanged() {
        LOG.i("onSurfaceChanged:", "Size is", getPreviewSurfaceSize(Reference.VIEW));
        getOrchestrator().scheduleStateful("surface changed", CameraState.BIND,
                new Runnable() {
                    @Override
                    public void run() {
                        // Compute a new camera preview size and apply.
                        Size newSize = computePreviewStreamSize();
                        if (newSize.equals(mPreviewStreamSize) || isTakingVideo()) {
                            LOG.i("onSurfaceChanged:",
                                    "The computed preview size is identical. No op.");
                        } else {
                            LOG.i("onSurfaceChanged:",
                                    "Computed a new preview size. Calling onPreviewStreamSizeChanged().");
                            mPreviewStreamSize = newSize;
                            onPreviewStreamSizeChanged();
                        }
                    }
                });
    }
```

Basically, if snapshot video is recording and even if surface change swallow that event and don't call  onPreviewStreamSizeChanged -> restartBind() in Camera2Engine class.

I haven't found any crash / issue during or after recording. Even though I still have a lot to understand in this amazing library but this could be my first contribution. And this small change can be helpful to add many other features. Please do provide you valuable feedback and if there are any other potential issues associated with this change.
