### ISSUE TITLE
How to use  CameraView library as .aar file or dependency module?

### ISSUE THREAD

**Issue by chitrang200889** [natario1/CameraView#885]
I need to modify the library a bit as mentioned in #862, #855, and #607. 

So after the changes in a clone of this project, I generated .aar file but it was crashing similar to #503. Also, I tried downloading .aar file from [here](https://jcenter.bintray.com/com/otaliastudios/cameraview/) but faced a similar issue.

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/otaliastudios/opengl/texture/GlTexture;
        at com.otaliastudios.cameraview.internal.GlTextureDrawer.<init>(GlTextureDrawer.java:35)
        at com.otaliastudios.cameraview.preview.GlCameraPreview$Renderer.onSurfaceCreated(GlCameraPreview.java:147)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1541)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.otaliastudios.opengl.texture.GlTexture" on path: DexPathList[[zip file "/data/app/madlipz.eigenuity.com-Tlb1HLmltCFCmunoMEtA9Q==/base.apk"],nativeLibraryDirectories=[/data/app/madlipz.eigenuity.com-Tlb1HLmltCFCmunoMEtA9Q==/lib/arm64, /data/app/madlipz.eigenuity.com-Tlb1HLmltCFCmunoMEtA9Q==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.otaliastudios.cameraview.internal.GlTextureDrawer.<init>(GlTextureDrawer.java:35) 
        at com.otaliastudios.cameraview.preview.GlCameraPreview$Renderer.onSurfaceCreated(GlCameraPreview.java:147) 
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1541) 
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272) 
```

Another solution I tried was to add the library as a module dependency. However, it requires to either **add** or **comment**  a lot of code related to apply plugin: 'com.github.dcendents.android-maven', apply plugin: 'com.jfrog.bintray' and maven installer. In addition to that, it loses the track with this original git repo which will add more complexity with future release if and when I require to upgrade the library. 

Please do suggest a stable solution that can comply with your future releases.

**Comment by natario1** [comment]
When you use an AAR file you have to add all the dependencies of the AAR project to your own project.

**Comment by chitrang200889** [comment]
I am following https://stackoverflow.com/a/50267507/3598052 this solution to generate .aar file which generates debug and release aar files. 

Is there any difference in the final builds? Which one should I use?

And this https://stackoverflow.com/a/49663101/3598052 to add & compile aar file.

**Comment by ppnfk** [comment]
@chitrang200889  after you add the aar into your project,  you could add the dependencies into your app's build.gradle. such as     **implementation 'com.otaliastudios.opengl:egloo:0.4.0'**
