### ISSUE TITLE
when open camera

### ISSUE THREAD

**Issue by dverdugo85** [natario1/CameraView#924]
### Describe the bug
Please add a clear description of what the bug is, **and** fill the list below.
- CameraView version: *version number*
- Camera engine used: *camera1/camera2/both*
- Reproducible in official demo app: *yes/no*
- Device / Android version: *Pixel, API 28*
- I have read the [FAQ page](https://natario1.github.io/CameraView/about/faq): *yes/no*

### To Reproduce
Steps to reproduce the behavior, possibly in the demo app:
2. Click on '...'
3. See error

  java.lang.IllegalStateException: This value is not sanitized: -552160
        at com.otaliastudios.cameraview.engine.offset.Angles.sanitizeInput(Angles.java:128)
        at com.otaliastudios.cameraview.engine.offset.Angles.setSensorOffset(Angles.java:41)
        at com.otaliastudios.cameraview.engine.Camera1Engine.collectCameraInfo(Camera1Engine.java:140)
        at com.otaliastudios.cameraview.engine.CameraEngine$5.call(CameraEngine.java:386)
        at com.otaliastudios.cameraview.engine.CameraEngine$5.call(CameraEngine.java:383)
        at com.otaliastudios.cameraview.engine.orchestrator.CameraStateOrchestrator$2.call(CameraStateOrchestrator.java:69)
        at com.otaliastudios.cameraview.engine.orchestrator.CameraStateOrchestrator$2.call(CameraStateOrchestrator.java:60)
        at com.otaliastudios.cameraview.engine.orchestrator.CameraOrchestrator$2.onComplete(CameraOrchestrator.java:100)
        at com.otaliastudios.cameraview.engine.orchestrator.CameraOrchestrator$4.run(CameraOrchestrator.java:195)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)

### XML layout
Part of the XML layout with the CameraView declaration, so we can read its attributes.

```xml
<CameraView
    android:layout_width="match_parent"
    android:layout_height="match_parent"       
    ...>
</CameraView>
```

### Logs
Use `CameraLogger.setLogLevel(LEVEL_INFO)` to see all logs into LogCat.

Use `CameraLogger.registerLogger()` to export to file or crash reporting service.

### APK
Link to a Github repo where the bug is reproducible.

**Comment by dverdugo85** [comment]
i put this

protected boolean collectCameraInfo(@NonNull Facing facing) {
        int internalFacing = mMapper.mapFacing(facing);
        for (int i = 0, count = Camera.getNumberOfCameras(); i < count; i++) {
            Camera.getCameraInfo(i, cameraInfo)
            if (cameraInfo.facing == internalFacing) {
                if(cameraInfo.orientation != 0)
                    if (cameraInfo.orientation == 0
                            || cameraInfo.orientation == 90
                            || cameraInfo.orientation == 180
                            || cameraInfo.orientation == 270
                            || cameraInfo.orientation == 360) {
                                getAngles().setSensorOffset(facing, cameraInfo.orientation);
                    } else {
                        getAngles().setSensorOffset(facing, 90);**//select 90 because I use the camera vertical always!**
                    }
                mCameraId = i;
                return true;
            }
        }
        return false;
    }

Regards!!
