### ISSUE TITLE
com.otaliastudios.cameraview.engine.Camera1Engine.getFrameManager()' on a null object reference

### ISSUE THREAD

**Issue by android-dataticket** [natario1/CameraView#993]
Please can you put a try catch on this line (line 84, Snapshot1PictureRecorder)

 mEngine1.getFrameManager().setUp(mFormat, previewStreamSize, mEngine1.getAngles());

this crash is frequent and affecting dearly

    java.lang.NullPointerException: Attempt to invoke virtual method 'com.otaliastudios.cameraview.frame.ByteBufferFrameManager com.otaliastudios.cameraview.engine.Camera1Engine.getFrameManager()' on a null object reference
        at com.otaliastudios.cameraview.picture.Snapshot1PictureRecorder$1.onPreviewFrame(Snapshot1PictureRecorder.java:84)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1221)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by android-dataticket** [comment]
I believe it's just because of using snapshot and taking photos extremely quickly - the dispatch method is stepping on itself when nulling out the Camera instance, causing the NPE when trying to set up the frame manager sporratically throughout the quick photo capture spree.. just a simple empty try catch on this line (or a if mEngine1 != null) stops the crash from happening and does not affect performance or functionality
